### ISSUE TITLE
ValueError: Minimization failed after 100 attempts

### ISSUE THREAD

**Issue by chenshixinnb** [YoshitakaMo/localcolabfold#108]
![image](https://user-images.githubusercontent.com/64191224/186342357-af479df4-6bf9-46fa-8a45-a86534511c24.png)
Recently, this problem has occurred in all runs

**Comment by YoshitakaMo** [comment]
Did you move the colabfold_batch directory from somewhere? If you moved it, the minimization step will fail.

**Comment by chenshixinnb** [comment]
> Did you move (or rename) the colabfold_batch directory from somewhere? If you moved it, the minimization step will fail.

no,I redeployed it today and the problem also occurred

**Comment by chenshixinnb** [comment]
I installed it from a script,After the installation is complete、export PATH、run

**Comment by YoshitakaMo** [comment]
Please show me the details:
- Results of `nvidia-smi -L` and `/path/to/nvcc --version`
- The execution command `colabfold_batch --amber --template ...` and its complete log messages.

**Comment by chenshixinnb** [comment]
`[cloudam@master ~]$ nvidia-smi -L
GPU 0: Tesla T4 (UUID: GPU-05c88ce7-ee31-0f33-2019-262c41c84afe)`

**Comment by chenshixinnb** [comment]
`[cloudam@master ~]$ /public/software/.local/easybuild/software/CUDA/11.1.1/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0`

**Comment by chenshixinnb** [comment]
`[cloudam@master work]$ colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax test.fasta outputdir
2022-08-25 09:23:16,269 Running colabfold 1.3.0 (a2b37ccccaf8336b68f2d716a18224dcce926658)
WARNING: You are welcome to use the default MSA server, however keep in mind that it's a limited shared resource only capable of processing a few thousand MSAs per day. Please submit jobs only from a single IP address. We reserve the right to limit access to the server case-by-case when usage exceeds fair use.

If you require more MSAs:

* You can precompute all MSAs with `colabfold_search` or

* You can host your own API and pass it to `--host-url`
2022-08-25 09:23:40,026 Could not open font file /usr/share/fonts/google-noto-emoji/NotoColorEmoji.ttf: In FT2Font: Can not load face.  Unknown file format.
2022-08-25 09:23:40,955 generated new fontManager
2022-08-25 09:23:56,439 Found 8 citations for tools or databases
2022-08-25 09:24:03,244 Query 1/1: sp_F6I457_AG11C_VITVI_Agamous-like_MADS-box_protein_AGL11_OS_Vitis_vinifera_OX_29760_GN_AGL11_PE_2_SV_1 (length 223)
COMPLETE: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [elapsed: 00:03 remaining: 00:00]
2022-08-25 09:24:16,079 Sequence 0 found templates: ['4ox0_B', '4ox0_D', '1mnm_A', '1k6o_B', '1k6o_C', '6wc2_C', '6bz1_B', '1hbx_D', '1hbx_E', '1n6j_A', '1egw_C', '1egw_D', '3mu6_D', '7nb0_A', '7nb0_D']
2022-08-25 09:24:17,419 Running model_3
2022-08-25 09:26:20,511 model_3 took 118.6s (3 recycles) with pLDDT 82.6 and ptmscore 0.401
Traceback (most recent call last):
  File "/public/software/.local/easybuild/software/ColabFold/colabfold_batch/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/public/software/.local/easybuild/software/ColabFold/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1765, in main
    stop_at_score_below=args.stop_at_score_below,
  File "/public/software/.local/easybuild/software/ColabFold/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1390, in run
    random_seed=random_seed,
  File "/public/software/.local/easybuild/software/ColabFold/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 479, in predict_structure
    relaxed_pdb_str, _, _ = amber_relaxer.process(prot=unrelaxed_protein)
  File "/public/software/.local/easybuild/software/ColabFold/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/alphafold/relax/relax.py", line 66, in process
    use_gpu=self._use_gpu)
  File "/public/software/.local/easybuild/software/ColabFold/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/alphafold/relax/amber_minimize.py", line 483, in run_pipeline
    use_gpu=use_gpu)
  File "/public/software/.local/easybuild/software/ColabFold/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/alphafold/relax/amber_minimize.py", line 419, in _run_one_iteration
    raise ValueError(f"Minimization failed after {max_attempts} attempts.")
ValueError: Minimization failed after 100 attempts.
`

**Comment by YoshitakaMo** [comment]
Does it work well without `--use-gpu-relax`?

**Comment by chenshixinnb** [comment]
> 如果您删除它是否可以正常工作`--use-gpu-relax`？

After removing it, it can run normally.
The output is normal.

**Comment by gancao** [comment]
I remove --use-gpu-relax， but the error still occurred.

**Comment by gancao** [comment]
nvidia-smi -L
GPU 0: NVIDIA A40 (UUID: GPU-3a0904e1-20fe-becb-1241-e7f57ae80815)

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0

**Comment by EgonHeuson** [comment]
Same issue here on M1 Mac. In my case I do not have a nvidia card of course 😅
```
File "/Users/xxxxx/opt/ColabFold/colabfold_batch/colabfold-conda/lib/python3.8/site-packages/alphafold/relax/amber_minimize.py", line 419, in _run_one_iteration
    raise ValueError(f"Minimization failed after {max_attempts} attempts.")
ValueError: Minimization failed after 100 attempts
```

**Comment by groponp** [comment]
This bug was fidex?, I also have same bug, not I'm sure as fix it.

**Comment by YoshitakaMo** [comment]
I freshly made the installer for ColabFold > 1.5.0 on Feb 6. Please try the installation again after removing the old one, and report whether the bug is fixed or not.

**Comment by EgonHeuson** [comment]
ok! I'll do this :-)

**Comment by YoshitakaMo** [comment]
> Maybe I should also remove the --use-gpu-relax argument if I want to use only the CPU?

Yes, `--use-gpu-relax` is not available on macOS since it has no NVIDIA GPUs. Moreover, the `--cpu` arg is now obsoleted from ColabFold 1.5.0.

> I tried reinstalling all required dependencies, as well as Python@3.8 using brew but same issue. :-(

Hmm, it seems tensorflow-cpu is not installed on your mac for some reason. Is your mac M1?
Now I've tested on my fresh Intel Mac with ColabFold 1.5.2, which is upgraded yesterday, and no errors detected. Since the implementation of the dependency has been updated, your issue may be solved with the latest version.

**Comment by Hypertyz** [comment]
This error occurs to me only when I run the code in a cluster. Weird.. I notice that the outputs are not reranked so i guess it failed to try to relax the 1st rank model. Here is the command I used:

`colabfold_batch --amber --num-relax 1 --use-gpu-relax --num-recycle 6 --zip --templates input_dir output_dir`

**Comment by Hypertyz** [comment]
I found a solution. Just remove `--use-gpu-relax` and it works!!

**Comment by jodo231** [comment]
Hi, 

Has there been any progress on this issue? I'm running into the same error. I did a fresh install yesterday (12/12/2023) using the bash script from the github and still ran into the same issues.

**Comment by gieses** [comment]
For me, the issues gets resolved with openmm==7.7.0 (mamba install openmm==7.7.0 -y)

**Comment by Gibo-Chun** [comment]
> For me, the issues gets resolved with openmm==7.7.0 (mamba install openmm==7.7.0 -y)

Very much thanks! This does help me!
