### ISSUE TITLE
FileExistsError: [Errno 17] File exists: '/home/rupesh/rupesh/colabfold/ecoli_aspartate_aminotransferase.fasta'

### ISSUE THREAD

**Issue by rupesh-sinha** [YoshitakaMo/localcolabfold#112]
I recently installed colabfold following https://github.com/YoshitakaMo/localcolabfold

The program seems to be installed perfectly when checked with `colabfold_batch --help

I wanted to predict structure of a protein which I am providing it in `input` argument like:

$ colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax input /home/rupesh/rupesh/colabfold/ecoli_aspartate_aminotransferase.fasta

but received following error:

Traceback (most recent call last):
  File "/home/rupesh/colabfold_batch/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/home/rupesh/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1703, in main
    setup_logging(Path(args.results).joinpath("log.txt"))
  File "/home/rupesh/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/utils.py", line 44, in setup_logging
    log_file.parent.mkdir(exist_ok=True, parents=True)
  File "/home/rupesh/colabfold_batch/colabfold-conda/lib/python3.7/pathlib.py", line 1273, in mkdir
    self._accessor.mkdir(self, mode)
**FileExistsError: [Errno 17] File exists: '/home/rupesh/rupesh/colabfold/ecoli_aspartate_aminotransferase.fasta'**

What is the reason for this error. Similar error appeared when I was trying to specify output directory with `results`
$ colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax input /home/rupesh/Desktop/ecoli_aspartate_aminotransferase.fasta results /home/rupesh/rupesh/fastq_aqua/

Error;

usage: colabfold_batch [-h] [--stop-at-score STOP_AT_SCORE]
                       [--stop-at-score-below STOP_AT_SCORE_BELOW]
                       [--num-recycle NUM_RECYCLE]
                       [--num-ensemble NUM_ENSEMBLE]
                       [--random-seed RANDOM_SEED] [--num-models {1,2,3,4,5}]
                       [--recompile-padding RECOMPILE_PADDING]
                       [--model-order MODEL_ORDER] [--host-url HOST_URL]
                       [--data DATA]
                       [--msa-mode {MMseqs2 UniRef+Environmental),MMseqs2 (UniRef only,single_sequence}]
                       [--model-type {auto,AlphaFold2-ptm,AlphaFold2-multimer-v1,AlphaFold2-multimer-v2}]
                       [--amber] [--templates]
                       [--custom-template-path CUSTOM_TEMPLATE_PATH] [--env]
                       [--cpu] [--rank {auto,plddt,ptmscore,multimer}]
                       [--pair-mode {unpaired,paired,unpaired+paired}]
                       [--recompile-all-models]
                       [--sort-queries-by {none,length,random}]
                       [--save-single-representations]
                       [--save-pair-representations] [--training]
                       [--max-msa {512:5120,512:1024,256:512,128:256,64:128,32:64,16:32}]
                       [--zip] [--use-gpu-relax]
                       [--overwrite-existing-results]
                       input results
**colabfold_batch: error: unrecognized arguments: results /home/rupesh/rupesh/fastq_aqua/**

Please help!

**Comment by YoshitakaMo** [comment]
> What is the reason for this error. Similar error appeared when I was trying to specify output directory with results
$ colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax input /home/rupesh/Desktop/ecoli_aspartate_aminotransferase.fasta results /home/rupesh/rupesh/fastq_aqua/

The command is not correct. Try
```bash
$ colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax /home/rupesh/Desktop/ecoli_aspartate_aminotransferase.fasta results /home/rupesh/rupesh/fastq_aqua/
```

**Comment by rupesh-sinha** [comment]
Many thanks Yoshitaka,
I tried this just a few second ago and the program is currently running. My command looks like

$ colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax /home/rupesh/Desktop/ecoli_aspartate_aminotransferase.fasta  /home/rupesh/rupesh/fastq_aqua/

Please note that I haven't used `results` to specify the output directory. Will it be a problem? Also wanted to know what are the files that I can expect to generate from this run. I am trying to predict structure of a protein sequence, is there any other structure refinement commands that need to be run after this?

Thanks a lot!

**Comment by YoshitakaMo** [comment]
You don't need to use `results` because it is just a placeholder. In other words, you should specify the output directory path instead of `results`.

> I am trying to predict structure of a protein sequence, is there any other structure refinement commands that need to be run after this?

No. The file whose name matches `*relaxed_rank_1*.pdb` is the best predicted structure.

**Comment by rupesh-sinha** [comment]
Thanks Yoshitaka,

I had run the colab_batch using the command described above for a single protein sequence.  Could you please suggest where I can get the exact PAE value for *relaxed_rank_1*.pdb prediction? I can see the pLDDT score in the log generated (pasted below), and I hope the pLDDT 44.9 for model 1 is the final score for *relaxed_rank_1*.pdb.  How useful is the ptmscore in this? As you can see the pLDDT score is quite low, can we improve the pLDDT of the prediction to >80 by increasing the --num-recycle to 12 (or something)?

2022-10-09 15:25:28,873 Running colabfold 1.3.0 (22671664ac2c9dcb30086c3e654414d950ccb297)
2022-10-09 15:25:30,732 Found 8 citations for tools or databases
2022-10-09 15:25:33,343 Query 1/1: 5 (length 217)
2022-10-09 15:25:34,137 Sleeping for 6s. Reason: PENDING
2022-10-09 15:25:40,815 Sleeping for 8s. Reason: RUNNING
2022-10-09 15:25:49,492 Sleeping for 6s. Reason: RUNNING
2022-10-09 15:25:56,161 Sleeping for 8s. Reason: RUNNING
2022-10-09 15:26:10,541 Sequence 0 found templates: ['3n08_B', '3n08_A', '4beg_A', '1fux_A', '1fux_B', '1fjj_A', '1fux_A', '1fux_B']
2022-10-09 15:26:11,141 Running model_3
2022-10-09 15:28:03,451 model_3 took 109.4s (3 recycles) with pLDDT 44.1 and ptmscore 0.319
2022-10-09 15:28:43,174 Relaxation took 31.6s
2022-10-09 15:28:43,174 Running model_4
2022-10-09 15:30:20,509 model_4 took 95.6s (3 recycles) with pLDDT 42.4 and ptmscore 0.311
2022-10-09 15:30:55,129 Relaxation took 26.2s
2022-10-09 15:30:55,141 Running model_5
2022-10-09 15:32:32,885 model_5 took 96.0s (3 recycles) with pLDDT 42.9 and ptmscore 0.311
2022-10-09 15:33:05,301 Relaxation took 24.6s
2022-10-09 15:33:05,301 Running model_1
2022-10-09 15:35:04,922 model_1 took 117.6s (3 recycles) with pLDDT 44.9 and ptmscore 0.328
2022-10-09 15:35:38,117 Relaxation took 25.1s
2022-10-09 15:35:38,118 Running model_2
2022-10-09 15:37:18,205 model_2 took 98.0s (3 recycles) with pLDDT 43 and ptmscore 0.306
2022-10-09 15:37:52,198 Relaxation took 26.6s
2022-10-09 15:37:52,198 reranking models by plddt
2022-10-09 15:37:54,176 Done

Many thanks!
