### ISSUE TITLE
Question: Is localcolabfold working on MacOS with Intel now?

### ISSUE THREAD

**Issue by jakubotreba** [YoshitakaMo/localcolabfold#124]
**What is your question?**
Describe your question here.

**Computational environment**
 - OS: macOS

**To Reproduce**
I am trying to run:
$ colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax $fasta_file ./outputs

**Expected behavior**
But I get the following error:

```
2022-12-09 15:44:46,834 Running colabfold 1.3.0 (5cadd359d5f878cee88db2d4555826a5e3eea24f)
Traceback (most recent call last):
  File "/Users/jakub/colabfold_batch/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/Users/jakub/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1735, in main
    from jax.lib import xla_bridge
  File "/Users/jakub/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/jax/__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "/Users/jakub/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/jax/config.py", line 17, in <module>
    from jax._src.config import config  # noqa: F401
  File "/Users/jakub/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/Users/jakub/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/jax/_src/lib/__init__.py", line 77, in <module>
    minimum_jaxlib_version=jax.version._minimum_jaxlib_version)
  File "/Users/jakub/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/jax/_src/lib/__init__.py", line 63, in check_jaxlib_version
    raise RuntimeError(msg)
RuntimeError: jaxlib is version 0.3.10, but this version of jax requires version >= 0.3.22.
```

I tried to uninstall colabfold and install again, tried to follow the steps of how "to fix this issue, please upgrade your jax and jaxlib", but the line: 

```
${COLABFOLDDIR}/colabfold-conda/bin/python3.7 -m pip install https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.3.25+cuda11.cudnn82-cp37-cp37m-manylinux2014_x86_64.whl
```

does not work on macos. I also tried to install jax via pip and it says that my version is 0.3.25. 
Do you maybe know what could be the problem?

**Comment by YoshitakaMo** [comment]
Since macOS doesn't support NVIDIA GPU, please remove `--use-gpu-relax`.

> RuntimeError: jaxlib is version 0.3.10, but this version of jax requires version >= 0.3.22.

Your localcolabfold is outdated now, please install again using the latest installer for macOS (Intel or M1 mac). The installer was tested on my both Intel and M1 Mac after removing `colabfold_batch` directory. 

> ${COLABFOLDDIR}/colabfold-conda/bin/python3.7 -m pip install https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.3.25+cuda11.cudnn82-cp37-cp37m-manylinux2014_x86_64.whl

Sorry, the upgrade instruction is only for Linux with GPU.

**Comment by YoshitakaMo** [comment]
Sorry, I forgot to update the install script for Intel Mac by mistake. Now it's been updated.
