### ISSUE TITLE
Question:Failed to establish connection: HTTPSConnectionPool

### ISSUE THREAD

**Issue by IlyesAbdelhamid** [YoshitakaMo/localcolabfold#125]
Hello,

I am using localcolabfold and I am experiencing for the first time failure in establishing connection with the API, after a couple of weeks not using localcolabfold. I've been using it for a long time now without experiencing this issue.
You will find below what it systematically returns for all my jobs. Thank you in advance for your help:

Module GCCcore/10.2.0, zlib/1.2.11, binutils/2.35, numactl/2.0.13, XZ/5.2.5, libxml2/2.9.10, libpciaccess/0.16, hwloc/2.2.0, libevent/2.1.12, UCX/1.9.0, libfabric/1.11.0, PMIx/3.1.5, GCC/10.2.0, CUDA/11.3.1, OpenMPI/4.0.5, GCC/10.2.0, OpenMPI/4.0.5, CUDA/11.3.1, OpenMPI/4.0.5 unloaded.
Module GCCcore/10.2.0zlib/1.2.11binutils/2.35numactl/2.0.13XZ/5.2.5libxml2/2.9.10libpciaccess/0.16hwloc/2.2.0libevent/2.1.12UCX/1.9.0libfabric/1.11.0PMIx/3.1.5GCC/10.2.0CUDA/11.3.1OpenMPI/4.0.5GCC/10.2.0OpenMPI/4.0.5CUDA/11.3.1OpenMPI/4.0.5 loaded.
sbatch run_colabfold_AF2Mv2_unpaired_paired_Human_Barabasi_top_signi_predicted_missing_links_dms.sh 4
Submitted batch job 31762849
WARNING: You are welcome to use the default MSA server, however keep in mind that it's a limited shared resource only capable of processing a few thousand MSAs per day. Please submit jobs only from a single IP address. We reserve the right to limit access to the server case-by-case when usage exceeds fair use.

If you require more MSAs:

* You can precompute all MSAs with `colabfold_search` or

* You can host your own API and pass it to `--host-url`
2022-12-10 12:23:38,061 Running colabfold 1.3.0 (7ebcbe62e8d88400b0e75aa0878dce2ff3a6c71f)
2022-12-10 12:23:38,929 --max-msa can not be used in combination with AlphaFold2-multimer (--max-msa ignored)
2022-12-10 12:23:41,743 Found 7 citations for tools or databases
2022-12-10 12:23:45,211 Query 1/1: O60674_P08581 (length 2522)

  0%|          | 0/300 [elapsed: 00:00 remaining: ?]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]
SUBMIT:   0%|          | 0/300 [elapsed: 02:07 remaining: ?]
2022-12-10 12:25:52,518 **Could not get MSA/templates for O60674_P08581: HTTPSConnectionPool(host='api.colabfold.com', port=443): Max retries exceeded with url: /ticket/msa (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b0fd6a80790>: Failed to establish a new connection: [Errno 110] Connection timed out'))**
Traceback (most recent call last):
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x2b0fd6a80790>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.colabfold.com', port=443): Max retries exceeded with url: /ticket/msa (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b0fd6a80790>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1429, in run
    host_url,
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 860, in get_msa_and_templates
    host_url=host_url,
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/colabfold.py", line 140, in run_mmseqs2
    out = submit(seqs_unique, mode, N)
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/colabfold.py", line 80, in submit
    res = requests.post(f'{host_url}/{submission_endpoint}', data={'q':query,'mode': mode})
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/lustre/ssd/ws/iabdelha-IA-AF-SSD-workspace/alphafold/data/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.colabfold.com', port=443): Max retries exceeded with url: /ticket/msa (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b0fd6a80790>: Failed to establish a new connection: [Errno 110] Connection timed out'))
2022-12-10 12:25:52,525 Done

**Comment by YoshitakaMo** [comment]
Is it related to https://github.com/YoshitakaMo/localcolabfold/issues/114 ?
