### ISSUE TITLE
MMseqs2 API is giving errors

### ISSUE THREAD

**Issue by TieliangGan** [YoshitakaMo/localcolabfold#129]
Hey it's me again! sorry to bother you guys during the holiday! Our lab recently are getting the following errors. We have made sure that the input sequence is valid and we have tried several times today and yesterday but the exception persists.

(base) [Pan_lab@localhost Desktop]$ colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax /home/Pan_lab/Desktop/inputfiles/53bp1_with_claw.fasta ./outputfiles/again
/home/Pan_lab/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/Bio/Data/SCOPData.py:21: BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  BiopythonDeprecationWarning,
2022-12-27 16:39:33,172 Running colabfold 1.3.0 (b0c8f4caa188eb8c2c5118d5b1af3ed1d97a248a)
2022-12-27 16:39:34,353 --max-msa can not be used in combination with AlphaFold2-multimer (--max-msa ignored)
WARNING: You are welcome to use the default MSA server, however keep in mind that it's a limited shared resource only capable of processing a few thousand MSAs per day. Please submit jobs only from a single IP address. We reserve the right to limit access to the server case-by-case when usage exceeds fair use.

If you require more MSAs:

* You can precompute all MSAs with `colabfold_search` or

* You can host your own API and pass it to `--host-url`
2022-12-27 16:39:37,368 Found 8 citations for tools or databases
2022-12-27 16:39:42,973 Query 1/1: 53bp1_1725-1972_with_RB1CC1_claw (length 353)
COMPLETE: 100%|██████████████████████| 300/300 [elapsed: 00:02 remaining: 00:00]
2022-12-27 16:39:58,544 Sequence 0 found templates: ['7czg_B', '7d0e_A', '7ea2_B', '6gma_D', '6gma_B', '7ea2_A', '6gma_B', '6gma_D']
2022-12-27 16:40:11,309 Sequence 1 found templates: ['1gzh_B', '1kzy_C', '2vxc_B', '2vxb_B', '4jlu_A', '4u4a_B', '4igk_B', '7p0l_A', '3al2_A', '7cmz_A', '6m14_B', '3t1n_A', '3u3z_A', '3sqd_A', '3sqd_B', '1l0b_A', '3k05_A', '3k05_B', '3l40_A', '3l41_A']
2022-12-27 16:40:15,150 Sleeping for 8s. Reason: PENDING                        
ERROR:   0%|                               | 0/300 [elapsed: 00:12 remaining: ?]
2022-12-27 16:40:23,983 Could not get MSA/templates for 53bp1_1725-1972_with_RB1CC1_claw: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
Traceback (most recent call last):
  File "/home/Pan_lab/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1361, in run
    host_url,
  File "/home/Pan_lab/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 842, in get_msa_and_templates
    host_url=host_url,
  File "/home/Pan_lab/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/colabfold.py", line 226, in run_mmseqs2
    raise Exception(f'MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.')
Exception: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
2022-12-27 16:40:23,984 Done
(base) [Pan_lab@localhost Desktop]$

in addition, we have encountered time stamp is in the future warning from tar(occasionally, not every time) but after we changed the system time, this problem seems to disappear.

Thanks a lot in advance for reviewing this issue!

**Comment by YoshitakaMo** [comment]
The MMseqs2 API is not the cause of this issue since colabfold and the API are normally running now.  First, you can try again with `--overwrite-existing-results` argument for `colabfold_batch`.

And I remember that you asked me about this issue https://github.com/YoshitakaMo/localcolabfold/issues/115, so I guess your environment variables such as PATH might do harm to the run of localcolabfold. Check your `~/.bashrc` (or `~/.bash_profile`, `~/.zshrc`), remove suspicious settings, and try the prediction again.

**Comment by TieliangGan** [comment]
ok thanks! as long as there is no problem on your side, we can close this issue now :) I believe I am able to handle it.
