### ISSUE TITLE
Question: Installation problems. Numpy?

### ISSUE THREAD

**Issue by allmanbrent** [YoshitakaMo/localcolabfold#131]
**Installation Problems?**
I had several issues while installing it. The first was that because I have spaces in some of my parent directories, the installation code could not point to the correct directories. I fixed this by changing the CURRENTPATH to `'.'`

I then was able to finish the installation, but ran into an issue with running collabfold_batch where packages seem incompatible.

**Computational environment**
 - OS: `$ uname -m
x86_64`

**To Reproduce**
1. My directory setup looks like:
Parent_dir 
->colabfold_batch
.....-update_intelmac.sh
.....->colabfold_batch
..........->bin
..........->colabfold-conda
..........->conda
2. I navigate to the directory `Parent_dir/colabfold_batch/colabfold_batch`
3. I then execute the following line and am met with this error message
> `colabfold_batch --help                                                                                                   
> Traceback (most recent call last):
>   File "/Users/beallma/miniconda3/bin/colabfold_batch", line 5, in <module>
>     from colabfold.batch import main
>   File "/Users/beallma/miniconda3/lib/python3.8/site-packages/colabfold/batch.py", line 33, in <module>
>     from alphafold.common import protein, residue_constants
>   File "/Users/beallma/miniconda3/lib/python3.8/site-packages/alphafold/common/protein.py", line 19, in <module>
>     from alphafold.common import residue_constants
>   File "/Users/beallma/miniconda3/lib/python3.8/site-packages/alphafold/common/residue_constants.py", line 774, in <module>
>     restype_atom37_to_rigid_group = np.zeros([21, 37], dtype=np.int)
>   File "/Users/beallma/miniconda3/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
>     raise AttributeError("module {!r} has no attribute "
> AttributeError: module 'numpy' has no attribute 'int'`

**Expected behavior**
When I run collabfold_batch I expect to be directed to the help menu so I can see the parameterlist. Thank you for any help you can provide! I am looking forward to running this program locally because of the constraints on Google Colab. This seems like it will be a great resource.

**Comment by Dongchengzhi** [comment]
I have the same problem. In my opinion, my GNU compiler version (4.8.5) leads to this.

**Comment by gieses** [comment]
You can monkey patch the file in the error by replacing np.int with np.int32. Numpy API has changed and does not allow np.int anymore.

Also see https://github.com/sokrypton/ColabDesign/issues/115

**Comment by dbolser** [comment]
Did this fix your issue?
