### ISSUE TITLE
Question: Installation issue on Mac M1 silicone

### ISSUE THREAD

**Issue by yhayashi0728** [YoshitakaMo/localcolabfold#144]
Hi.  I have problem in installing AlphaFold2 locally in my MacBook Pro (M1 silicone)

**Computational environment**
 - OS: macOS 13.2.1

**To Reproduce**
I am novice to AlphaFold2 or Unix system. I believe I exactly followed the instruction and get the following message.  It appears that I have a x86_64 version of "tree".  But even after I removed all softwares installed by Homebrew and reinstalled AlphaFold2, the situation does not change.  

Thanks.

---------

(base) Epinephrine3:localcolabfold yasunorihayashi$ colabfold_batch --amber --templates --num-recycle 3 inputfile outputdir/ 
Traceback (most recent call last):
  File "/Users/yasunorihayashi/localcolabfold/colabfold-conda/bin/colabfold_batch", line 5, in <module>
    from colabfold.batch import main
  File "/Users/yasunorihayashi/localcolabfold/colabfold-conda/lib/python3.9/site-packages/colabfold/batch.py", line 38, in <module>
    from alphafold.common import protein, residue_constants
  File "/Users/yasunorihayashi/localcolabfold/colabfold-conda/lib/python3.9/site-packages/alphafold/common/protein.py", line 19, in <module>
    from alphafold.common import residue_constants
  File "/Users/yasunorihayashi/localcolabfold/colabfold-conda/lib/python3.9/site-packages/alphafold/common/residue_constants.py", line 23, in <module>
    import tree
  File "/Users/yasunorihayashi/localcolabfold/colabfold-conda/lib/python3.9/site-packages/tree/__init__.py", line 23, in <module>
    from .sequence import _is_attrs
  File "/Users/yasunorihayashi/localcolabfold/colabfold-conda/lib/python3.9/site-packages/tree/sequence.py", line 19, in <module>
    from tree import _tree
ImportError: dlopen(/Users/yasunorihayashi/localcolabfold/colabfold-conda/lib/python3.9/site-packages/tree/_tree.cpython-39-darwin.so, 0x0002): tried: '/Users/yasunorihayashi/localcolabfold/colabfold-conda/lib/python3.9/site-packages/tree/_tree.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/yasunorihayashi/localcolabfold/colabfold-conda/lib/python3.9/site-packages/tree/_tree.cpython-39-darwin.so' (no such file), '/Users/yasunorihayashi/localcolabfold/colabfold-conda/lib/python3.9/site-packages/tree/_tree.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by yhayashi0728** [comment]
According to the previous thread,

https://github.com/YoshitakaMo/localcolabfold/issues/103

I removed /usr/local/ folder, uninstall anything installed by Homebrew, and re-installed Colabfold.  I got warnings saying some components are missing but I managed install them by Homebrew, PIP or Conda.  Now Colabfold seems to be working.

Thanks.
