### ISSUE TITLE
prep_model_runnerのバグ？

### ISSUE THREAD

**Issue by sotanengel** [YoshitakaMo/localcolabfold#16]
# バグの内容
## 実行環境

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
```

## 実行コマンド

```
colabfold-conda/bin/python3.7 runner_af2advanced.py \
--input hoge.fasta \
--output_dir hoge \
--max_recycle 6 \
--msa_method single_sequence \
--num_relax Top5
```

## エラー内容

```
Traceback (most recent call last):
  File "runner_af2advanced.py", line 248, in <module>
    rank_by=rank_by, show_images=show_images)
  File "colabfold/colabfold_alphafold.py", line 775, in run_alphafold
    model_runner = prep_model_runner(opt, model_name=model_name, use_turbo=False, params_loc=params_loc)["model"]
TypeError: prep_model_runner() got an unexpected keyword argument 'use_turbo'
```

# 問題の推測
cf_af.run_alphafoldに渡しているoptの中で`use_turbo`を定義してしまっているからでしょうか？
https://github.com/YoshitakaMo/localcolabfold/blob/34c1035e549a79b70a9c716e64511d24b6121d75/runner_af2advanced.py#L222-L231

# 解決方法
上記のoptを定義するときに`use_turbo `の部分を削除することで解決できるでしょうか？

**Comment by YoshitakaMo** [comment]
Merged. Thank you for your PR. 
However, this seems to be caused by insufficient function definitions in the `colabfold_alphafold.py`. If this python is fixed in the future, I need to modify the runner again.
