### ISSUE TITLE
Dear developer im having following error while running localcolabfold in GPU @ HPC, how to resolve this error? 

### ISSUE THREAD

**Issue by MuthusaravananS** [YoshitakaMo/localcolabfold#179]
2023-09-30 16:50:57.340222: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:767] failed to alloc 47987818496 bytes unified memory; result: CUDA_ERROR_INVALID_VALUE: invalid argument
2023-09-30 16:50:57.340294: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:767] failed to alloc 43189035008 bytes unified memory; result: CUDA_ERROR_INVALID_VALUE: invalid argument
2023-09-30 16:50:57.340315: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:767] failed to alloc 38870130688 bytes unified memory; result: CUDA_ERROR_INVALID_VALUE: invalid argument
2023-09-30 16:50:57.340332: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:767] failed to alloc 34983116800 bytes unified memory; result: CUDA_ERROR_INVALID_VALUE: invalid argument
2023-09-30 16:50:57.340350: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:767] failed to alloc 31484805120 bytes unified memory; result: CUDA_ERROR_INVALID_VALUE: invalid argument
Traceback (most recent call last):
  File "/home/balakumaran.c/localcolabfold-1.5.2/localcolabfold/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/home/balakumaran.c/localcolabfold-1.5.2/localcolabfold/colabfold-conda/lib/python3.9/site-packages/colabfold/batch.py", line 349, in main
    run(queries=queries, **run_params)
  File "/home/balakumaran.c/localcolabfold-1.5.2/localcolabfold/colabfold-conda/lib/python3.9/site-packages/colabfold/run_alphafold.py", line 353, in run
    results = predict_structure(
  File "/home/balakumaran.c/localcolabfold-1.5.2/localcolabfold/colabfold-conda/lib/python3.9/site-packages/colabfold/predict.py", line 49, in predict_structure
    from colabfold.alphafold.relax import run_relax
  File "/home/balakumaran.c/localcolabfold-1.5.2/localcolabfold/colabfold-conda/lib/python3.9/site-packages/colabfold/alphafold/relax.py", line 5, in <module>
    from alphafold.relax import relax
  File "/home/balakumaran.c/localcolabfold-1.5.2/localcolabfold/colabfold-conda/lib/python3.9/site-packages/alphafold/relax/relax.py", line 18, in <module>
    from alphafold.relax import amber_minimize
  File "/home/balakumaran.c/localcolabfold-1.5.2/localcolabfold/colabfold-conda/lib/python3.9/site-packages/alphafold/relax/amber_minimize.py", line 25, in <module>
    from alphafold.relax import cleanup
  File "/home/balakumaran.c/localcolabfold-1.5.2/localcolabfold/colabfold-conda/lib/python3.9/site-packages/alphafold/relax/cleanup.py", line 22, in <module>
    import pdbfixer
  File "/home/balakumaran.c/localcolabfold-1.5.2/localcolabfold/colabfold-conda/lib/python3.9/site-packages/pdbfixer/__init__.py", line 2, in <module>
    from .pdbfixer import PDBFixer
  File "/home/balakumaran.c/localcolabfold-1.5.2/localcolabfold/colabfold-conda/lib/python3.9/site-packages/pdbfixer/pdbfixer.py", line 35, in <module>
    import simtk.openmm as mm
  File "/home/balakumaran.c/localcolabfold-1.5.2/localcolabfold/colabfold-conda/lib/python3.9/site-packages/simtk/openmm/__init__.py", line 19, in <module>
    from simtk.openmm.openmm import *
  File "/home/balakumaran.c/localcolabfold-1.5.2/localcolabfold/colabfold-conda/lib/python3.9/site-packages/simtk/openmm/openmm.py", line 13, in <module>
    from . import _openmm
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/balakumaran.c/localcolabfold-1.5.2/localcolabfold/colabfold-conda/lib/python3.9/site-packages/simtk/openmm/_openmm.cpython-39-x86_64-linux-gnu.so)

**Comment by YoshitakaMo** [comment]
The last import error `/lib64/libstdc++.so.6: version GLIBCXX_3.4.20' not found` may be caused by very old GCC compiler.
Please check your gcc version. See also the instruction 3 https://github.com/YoshitakaMo/localcolabfold#for-linux .

**Comment by MuthusaravananS** [comment]
Thanks for your prompt reply.
