### ISSUE TITLE
Error: Read-only file system: '/cvmfs/datahub.genap.ca/vhost34/colabfold_db/params'

### ISSUE THREAD

**Issue by jflucier** [YoshitakaMo/localcolabfold#184]
Hi

I looked in issues and doc and did not find the answer to this error. I have downloaded the colabfold database and published it on a read-only filesystem. When I execute `colabfold_batch` I get this error:

```
2023-10-10 13:05:18,360 Running colabfold 1.5.2 (3e99c44eec189ec27f6d120af851adb7ff6aa2a2)
Traceback (most recent call last):
  File "/lustre03/project/6003342/programs/colabfold_env/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/lustre03/project/6003342/programs/colabfold_env/lib/python3.8/site-packages/colabfold/batch.py", line 1762, in main
    download_alphafold_params(model_type, data_dir)
  File "/lustre03/project/6003342/programs/colabfold_env/lib/python3.8/site-packages/colabfold/download.py", line 41, in download_alphafold_params
    params_dir.mkdir(parents=True, exist_ok=True)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.10/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [Errno 30] Read-only file system: '/cvmfs/datahub.genap.ca/vhost34/colabfold_db/params'

```

It is trying to write in a params folder. The command I use to generate this error is the following:
```
export DOWNLOAD_DIR=/cvmfs/datahub.genap.ca/vhost34/colabfold_db
export INPUT_DIR=/home/jflucier/projects/def-marechal/analysis/20230922_fold
export OUTPUT_DIR=/home/jflucier/projects/def-marechal/analysis/20230922_fold/rfwd3_colab_out
export PDB_DIR=/home/jflucier/projects/def-marechal/analysis/20230922_fold/pdb

echo "running colabfold locally on ${INPUT_DIR}/rfwd3_dimers.fasta"
#https://github.com/google-deepmind/alphafold/issues/344
#--max_template_date=2021-12-31 --> 3000-01-01
# --num-recycle 10 \
colabfold_batch \
--num-models 3 \
--use-gpu-relax --amber --num-relax 3 \
--num-recycle 30 --recycle-early-stop-tolerance 0.5 \
--templates --custom-template-path $PDB_DIR \
--model-type alphafold2_multimer_v3 \
--data $DOWNLOAD_DIR \
$INPUT_DIR/rfwd3_dimers.fasta \
$OUTPUT_DIR

Dont konw if it is linked to this, but my In the PDB_DIR contains 2 pdb files. 

Is the params folder created only on first start of colabfold or at every launch? If it is a one time only, I could run `colabfold_batch` until this step is complete and republish db folder in read only filesystem.

Thank again for your help,
JF

```

**Comment by jflucier** [comment]
Hello again,

I tried solution I described above: I run on login node with internet access and it generated the params folder. However, when I launch analysis on compute node, it still tries to connect to msa server:

```
2023-10-11 07:06:49,281 Error: HTTPSConnectionPool(host='api.colabfold.com', port=443): Max retries exceeded with url: /ticket/msa (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b1e1f498d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-10-11 07:06:54,292 Error while fetching result from MSA server. Retrying... (1/5)
2023-10-11 07:06:54,293 Error: HTTPSConnectionPool(host='api.colabfold.com', port=443): Max retries exceeded with url: /ticket/msa (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b1e20bdde20>: Failed to establish a new connection: [Errno 111] Connection refused'))

```

Is there something else I need to download or doI need to modify my call with colabfold_batch. Here is my submittion script:
```
#!/bin/bash

#SBATCH --job-name=rfwd3_alphafold
#SBATCH -D /home/jflucier/projects/def-marechal/analysis/20230922_fold/rfwd3_colab_out
#SBATCH -o /home/jflucier/projects/def-marechal/analysis/20230922_fold/rfwd3_colab_out/slurm-%A_%a.out
#SBATCH --account=def-marechal
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1
#SBATCH --mem=40G

source /home/jflucier/projects/def-marechal/programs/colabfold_env/bin/activate
module load mmseqs2/14-7e284

export TF_FORCE_UNIFIED_MEMORY="1"
export XLA_PYTHON_CLIENT_MEM_FRACTION="4.0"
export XLA_PYTHON_CLIENT_ALLOCATOR="platform"
export TF_FORCE_GPU_ALLOW_GROWTH="true"

export DOWNLOAD_DIR=/cvmfs/datahub.genap.ca/vhost34/colabfold_db
export INPUT_DIR=/home/jflucier/projects/def-marechal/analysis/20230922_fold
export OUTPUT_DIR=/home/jflucier/projects/def-marechal/analysis/20230922_fold/rfwd3_colab_out
export PDB_DIR=/home/jflucier/projects/def-marechal/analysis/20230922_fold/pdb

echo "running colabfold locally on ${INPUT_DIR}/rfwd3_dimers.fasta"
#https://github.com/google-deepmind/alphafold/issues/344
#--max_template_date=2021-12-31 --> 3000-01-01
# --num-recycle 10 \
colabfold_batch \
--num-models 3 \
--use-gpu-relax --amber --num-relax 3 \
--num-recycle 30 --recycle-early-stop-tolerance 0.5 \
--templates --custom-template-path $PDB_DIR \
--model-type alphafold2_multimer_v3 \
--data $DOWNLOAD_DIR \
$INPUT_DIR/rfwd3_dimers.fasta \
$OUTPUT_DIR

echo "done!"

```

Thanks for your help,
JF

**Comment by YoshitakaMo** [comment]
As explained in https://github.com/YoshitakaMo/localcolabfold/issues/181, you need to run `colabfold_batch` to obtain MSA and templates beforehand. If you obtain an a3m-formatted MSA file by running `colabfold_search` locally, you specify it as `$INPUT_DIR/rfwd3_dimers.a3m` instead of `$INPUT_DIR/rfwd3_dimers.fasta`. If you specify fasta-formatted file as input, then `colabfold_batch` will try to obtain MSA and templates through Internet unless they already exist in the $OUTPUT_DIR.

However, unfortunately, the pipeline to include template information without Internet connection is not yet fully implemented (though MSA can be obtained by using `colabfold_search`).

**Comment by jflucier** [comment]
we opened network on compute node for domain api.colabfold.com and it worked. 
Thanks for your help
