### ISSUE TITLE
Question: GLIBCXX_3.4.26 not found

### ISSUE THREAD

**Issue by Leo-T-Zang** [YoshitakaMo/localcolabfold#185]
Hi @YoshitakaMo,

**What is your installation issue?**

When I run colabfold command recently, I encounter error below. I have used it for couple months and it worked very well.
```
2023-10-12 22:05:33.151826: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "colabfold/localcolabfold/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1797, in main
    run(
  File "/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1473, in run
    results = predict_structure(
  File "/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 529, in predict_structure
    pdb_lines = relax_me(pdb_lines=unrelaxed_pdb_lines[key], use_gpu=use_gpu_relax)
  File "/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 300, in relax_me
    from alphafold.relax import relax
  File "/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/relax/relax.py", line 18, in <module>
    from alphafold.relax import amber_minimize
  File "/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/relax/amber_minimize.py", line 25, in <module>
    from alphafold.relax import cleanup
  File "/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/relax/cleanup.py", line 22, in <module>
    import pdbfixer
  File "/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pdbfixer/__init__.py", line 2, in <module>
    from .pdbfixer import PDBFixer
  File "//tianlai/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pdbfixer/pdbfixer.py", line 35, in <module>
    import openmm as mm
  File "/tianlai/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/openmm/__init__.py", line 19, in <module>
    from openmm.openmm import *
  File "/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/openmm/openmm.py", line 13, in <module>
    from . import _openmm
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/open$
```

**Computational environment**

OS
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: AlmaLinux
Description:    AlmaLinux release 8.8 (Sapphire Caracal)
Release:        8.8
Codename:       SapphireCaracal
```

```
gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18)

```

Do you have idea how to solve it? Thanks.

**Comment by YoshitakaMo** [comment]
Oh, openmm requires GLIBCXX_3.4.26, which is included in gcc version 9 or later. Thus, installing newer gcc will solve this issue. I have to update the README.
