### ISSUE TITLE
 TimeoutError during installation

### ISSUE THREAD

**Issue by YuanwenGuo** [YoshitakaMo/localcolabfold#198]
Hi localcolafold team,

Thank you developing such as a fascinating tool! I tired to install it on our HPC system, it worked well until the following error popped out:

Downloading tensorflow_cpu-2.12.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (231.8 MB)
   ━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━ 95.8/231.8 MB 13.9 kB/s eta 2:42:38
ERROR: Exception:
Traceback (most recent call last):
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/http/client.py", line 466, in read
    s = self.fp.read(amt)
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 179, in resolve
    self.factory.preparer.prepare_linked_requirements_more(reqs)
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 552, in prepare_linked_requirements_more
    self._complete_partial_requirements(
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 467, in _complete_partial_requirements
    for link, (filepath, _) in batch_download:
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pip/_internal/network/download.py", line 183, in __call__
    for chunk in chunks:
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
    with self._error_catcher():
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/public/home/gongziwen/tools/colab/localcolabfold/colabfold-conda/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

Could you please let me know how to deal this issue? Thanks a lot!

Yuanwen

**Comment by YuanwenGuo** [comment]
Solved by adding "--default-timeout=100"
