### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by dcbmariano** [YoshitakaMo/localcolabfold#199]
Hey,

I'm trying to install on an m1 mac but I'm getting a lot of errors. Initially, I followed the tutorial, but there was an error in the JAX library. I solved it by updating the library using Anaconda.

Now I'm having this coding error that I can't find the source. Has anyone ever experienced this?

<code>diego@hipogrifo colabfold-conda % bin/colabfold_batch teste output
2023-12-10 22:19:58,632 Running colabfold 1.5.3 (ca6b297021bb876157b75d84d591ed350cbece85)
Traceback (most recent call last):
  File "/Volumes/Hermes/alphafold/localcolabfold/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/Volumes/Hermes/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1998, in main
    queries, is_complex = get_queries(args.input, args.sort_queries_by)
  File "/Volumes/Hermes/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 623, in get_queries
    (seqs, header) = parse_fasta(file.read_text())
  File "/Volumes/Hermes/alphafold/localcolabfold/colabfold-conda/lib/python3.10/pathlib.py", line 1135, in read_text
    return f.read()
  File "/Volumes/Hermes/alphafold/localcolabfold/colabfold-conda/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte

</code>

**Comment by dcbmariano** [comment]
For some reason, it does not work when a pass a directory as input, but works when I pass a fasta file directly.
