### ISSUE TITLE
Question: localcolabfold error "ValueError: min() arg is an empty sequence" when it predicts trimer complex

### ISSUE THREAD

**Issue by Tttgb** [YoshitakaMo/localcolabfold#202]
Dear developer:
**I ran the localcolabfold very successfully when it predicted dimer complex. However when it encounter trimer complex, it fails, even though their linux code is the same.**
Here are the output of localcolabfold：

> 2023-12-20 13:11:36.499095: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-12-20 13:11:44.437896: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1956] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-12-20 13:11:26,716 Running colabfold 1.5.3 (5bb28b0de8d1f9fdedbe66e94c8fc61b6fa8c695)
2023-12-20 13:11:44,428 Running on GPU
2023-12-20 13:11:46,007 Found 8 citations for tools or databases
2023-12-20 13:14:30,835 Query 1/1: GPATCH8_1_1502__SF3B1_453_1304__DHX15_1_795_ (length 3149)
2023-12-20 13:18:43,618 Sequence 0 found templates: ['6sh7_B', '8ejm_B', '6sh6_B', '7onb_N', '7q4o_9', '7q4p_9', '7abh_4', '6ahd_w', '5z56_w', '6ah0_w', '7abi_N', '5o9z_N', '7abg_N', '6ahd_8', '7dco_y']
2023-12-20 13:19:22,887 Could not get MSA/templates for GPATCH8_1_1502__SF3B1_453_1304__DHX15_1_795_: min() arg is an empty sequence
Traceback (most recent call last):
  File "/data/run01/scv3554/xrh/xjd/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1470, in run
    = get_msa_and_templates(jobname, query_seqs_unique, unpaired_msa, result_dir, 'single_sequence', use_templates,
  File "/data/run01/scv3554/xrh/xjd/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 782, in get_msa_and_templates
    template_feature = mk_template(
  File "/data/run01/scv3554/xrh/xjd/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 134, in mk_template
    templates_result = template_featurizer.get_templates(
  File "/data/run01/scv3554/xrh/xjd/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/data/templates.py", line 883, in get_templates
    result = _process_single_hit(
  File "/data/run01/scv3554/xrh/xjd/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/data/templates.py", line 715, in _process_single_hit
    mapping = _build_query_to_hit_index_mapping(
  File "/data/run01/scv3554/xrh/xjd/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/data/templates.py", line 646, in _build_query_to_hit_index_mapping
    min_idx = min(x for x in indices_query if x > -1)
ValueError: min() arg is an empty sequence
2023-12-20 13:19:22,893 Done

The code I run colabfold is:  `colabfold_batch --templates --amber --custom-template-path ./template/ ./*.a3m ./output` ,and the .a3m file and the template files are pre-generated. 

This appears to be a bug when using .a3m files to start predictions, because I don't get this error when I try to start from a fastp file. Maybe it is related with #182 ?

Thanks!

**Comment by Tttgb** [comment]
Here is the output when I try to start with a fastp file: 

> 2023-12-20 15:30:59,822 Running colabfold 1.5.3 (223e4bfba3aaef902cc96810ba8947b04e7b4b28)
2023-12-20 15:32:19.024163: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-12-20 15:32:48,795 Running on GPU
2023-12-20 15:32:49.227967: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1956] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-12-20 15:33:00,196 Found 8 citations for tools or databases
2023-12-20 15:33:00,197 Query 1/1: GPATCH8_1_1502__SF3B1_453_1304__DHX15_1_795_ (length 3149)
COMPLETE: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 450/450 [elapsed: 00:19 remaining: 00:00]
2023-12-20 15:33:55,334 Sequence 0 found templates: ['6sh6_B', '6sh7_B', '8ejm_B']
2023-12-20 15:36:46,166 Sequence 1 found templates: ['7dvq_1', '6qx9_B1', '7abh_u', '7b92_C', '5z56_1', '6ahd_1', '7abi_u', '6ah0_1', '7abg_u', '5ife_C', '7q4o_A', '7onb_C', '5zya_C', '7dco_1', '6g90_O', '5lqw_Q', '7q4p_A', '6fsq_A', '7dvq_1', '6qx9_B1']
2023-12-20 15:37:57,369 Sequence 2 found templates: ['5xdr_A', '6sh6_A', '8ejm_A', '6sh7_A', '6id1_V', '2xau_A', '5lta_A', '6qie_A', '6qid_A', '3kx2_B', '5jpt_B', '5xjc_Y', '6i3p_C', '6qic_C', '6i3p_B', '6i3p_A', '6hyt_D', '5y88_W']
COMPLETE: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 450/450 [elapsed: 00:05 remaining: 00:00]
^CTraceback (most recent call last):
  File "/home/Liulab/xiejd/software/colabfold/localcolabfold/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/home/Liulab/xiejd/software/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 2022, in main
    run(
  File "/home/Liulab/xiejd/software/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1483, in run
    = generate_input_feature(query_seqs_unique, query_seqs_cardinality, unpaired_msa, paired_msa,
  File "/home/Liulab/xiejd/software/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1010, in generate_input_feature
    feature_dict = build_monomer_feature(
  File "/home/Liulab/xiejd/software/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 866, in build_monomer_feature
    **pipeline.make_msa_features([msa]),
  File "/home/Liulab/xiejd/software/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/data/pipeline.py", line 80, in make_msa_features
    features['msa'] = np.array(int_msa, dtype=np.int32)
KeyboardInterrupt
