### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by niubo-xingshen** [YoshitakaMo/localcolabfold#208]
colabfold_batch /data/text.fasta /data/zzq_NC/temp/clf
2024-01-21 23:19:06,148 Running colabfold 1.5.5
Traceback (most recent call last):
  File "/data/clf/localcolabfold/colabfold-conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/data/clf/localcolabfold/colabfold-conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/data/clf/localcolabfold/colabfold-conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/data/clf/localcolabfold/colabfold-conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/data/clf/localcolabfold/colabfold-conda/lib/python3.10/site-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/data/clf/localcolabfold/colabfold-conda/lib/python3.10/site-packages/urllib3/connection.py", line 782, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/data/clf/localcolabfold/colabfold-conda/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 470, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/data/clf/localcolabfold/colabfold-conda/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 514, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/data/clf/localcolabfold/colabfold-conda/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/data/clf/localcolabfold/colabfold-conda/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/data/clf/localcolabfold/colabfold-conda/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

**Comment by YoshitakaMo** [comment]
In many cases, the issue arises because the computational environment running ColabFold doesn't allow Internet connection or experiences connectivity problems (around SSL). If you're using a supercomputer, it's possible that the compute nodes may not permit Internet access. Please consult your network administrator for more details on this issue.

**Comment by niubo-xingshen** [comment]
Thank you! by the way，Is there a way to use it locally and bypass network access?
