### ISSUE TITLE
ValueError: Minimization failed after 100 attempts.

### ISSUE THREAD

**Issue by jodo231** [YoshitakaMo/localcolabfold#215]
Hello. 

I recently installed the newest version of localcolabfold (v1.5.5) on a server with 152 CPU cores and 4 NVIDIA gpus. Installation was carried out following localcolabfold installation script from the documentation and no errors were seen.  

I am able to run localcolabfold to predict protein structures using a GPU and relax the structure using CPUs, however if i use the --use-gpu-relax flag to minimise the predictions, i get an error stating "Minimization failed after 100 attempts". 

The input and error message can be seen here: 

colabfold_batch --templates --amber --use-gpu-relax --num-models 1 1.fasta output/
2024-02-23 12:16:02,104 Running colabfold 1.5.5 (2ecbcb352b90faba181771888e506d19b8d7256b)
2024-02-23 12:16:10,122 Running on GPU
2024-02-23 12:16:10,669 Found 9 citations for tools or databases
2024-02-23 12:16:10,669 Query 1/1: Fc1 (length 232)
2024-02-23 12:16:18,771 Sequence 0 found templates: ['1hzh_H', '1hzh_K', '5dk3_B', '5dk3_G', '1mco_H', '5v4e_H', '6d4m_A', '5v4e_A', '6d4n_B', '7wso_B', '8a47_B', '7x13_D', '3c2s_A', '4x98_A', '3v8c_B', '4j12_A', '3dnk_A', '6ifj_B', '2j6e_B', '5bw7_A']
2024-02-23 12:16:19,392 Setting max_seq=512, max_extra_seq=4829
2024-02-23 12:19:59,499 alphafold2_ptm_model_1_seed_000 recycle=0 pLDDT=92 pTM=0.804
2024-02-23 12:20:03,143 alphafold2_ptm_model_1_seed_000 recycle=1 pLDDT=92.4 pTM=0.82 tol=0.624
2024-02-23 12:20:06,754 alphafold2_ptm_model_1_seed_000 recycle=2 pLDDT=92.6 pTM=0.821 tol=0.21
2024-02-23 12:20:10,319 alphafold2_ptm_model_1_seed_000 recycle=3 pLDDT=92.6 pTM=0.819 tol=0.14
2024-02-23 12:20:10,320 alphafold2_ptm_model_1_seed_000 took 212.2s (3 recycles)
2024-02-23 12:20:10,383 reranking models by 'plddt' metric
2024-02-23 12:20:14,963 Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Traceback (most recent call last):
  File "/home/bin/localcolabfold/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/home/bin/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 2037, in main
    run(
  File "/home/bin/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1575, in run
    results = predict_structure(
  File "/home/bin/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 523, in predict_structure
    pdb_lines = relax_me(
  File "/home/bin/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/relax.py", line 30, in relax_me
    relaxed_pdb_lines, _, _ = amber_relaxer.process(prot=pdb_obj)
  File "/home/bin/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/relax/relax.py", line 62, in process
    out = amber_minimize.run_pipeline(
  File "/home/bin/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/relax/amber_minimize.py", line 476, in run_pipeline
    ret = _run_one_iteration(
  File "/home/bin/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/relax/amber_minimize.py", line 420, in _run_one_iteration
    raise ValueError(f"Minimization failed after {max_attempts} attempts.")
ValueError: Minimization failed after 100 attempts.

Computational environment

 - OS: Centos 7
 - CUDA version: 11.8

Could you please advise on this issue.

**Comment by YoshitakaMo** [comment]
This issue has arisen several times, but I don't yet understand the fundamental cause. For the time being, you can either refrain from using `--use-gpu-relax` or exclude `--amber` to output only the unrelaxed structures. Afterward, you can perform only the relaxation process on the jupyter notebook https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/beta/relax_amber.ipynb to obtain the relaxed structures for the input unrelaxed ones.

**Comment by dbolser** [comment]
Can you try the latest cuda version?
