### ISSUE TITLE
TLS/SSL connection issue on Docker desktop

### ISSUE THREAD

**Issue by AzumaSerenThePatriot** [YoshitakaMo/localcolabfold#231]
I'm running colabfold on centos7 on docker with windows11, and it comes out immediately when I start the prediction:

Traceback (most recent call last):
  File "/software/colab/localcolabfold/colabfold-conda/lib/python3.9/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/software/colab/localcolabfold/colabfold-conda/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/software/colab/localcolabfold/colabfold-conda/lib/python3.9/site-packages/urllib3/connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/software/colab/localcolabfold/colabfold-conda/lib/python3.9/site-packages/urllib3/connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/software/colab/localcolabfold/colabfold-conda/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/software/colab/localcolabfold/colabfold-conda/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/software/colab/localcolabfold/colabfold-conda/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/software/colab/localcolabfold/colabfold-conda/lib/python3.9/ssl.py", line 1074, in _create
    self.do_handshake()
  File "/software/colab/localcolabfold/colabfold-conda/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1133)

1. Using the newest localcolabfold (1.5.5) doesn't change anything.
2. It doesn't look like a connection problem: my M2 Mac can use localcolabfold properly under the same network.
3. These issues come out immediately when I use colabfold_batch.

**Comment by YoshitakaMo** [comment]
In most cases, TLS/SSL connection issue is attributed to the network configuration or lack of SSL configuration. I'm not familiar with Docker, but did you do `update-ca-trust`? https://stackoverflow.com/questions/37043442/how-to-add-certificate-authority-file-in-centos-7
