### ISSUE TITLE
code error running colabfold_batch with custom templates

### ISSUE THREAD

**Issue by bioinfcib** [YoshitakaMo/localcolabfold#271]
Hi,
First of all, I'd like to thank you for making freely available your software development.

The following command line:
colabfold_batch --templates --amber --num-relax 1 target.fasta --custom-template-path ./my_template results_dir

ends with the next error code lines:
Traceback (most recent call last):
  File "/home/mario/Colabfold/localcolabfold/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/home/mario/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 2046, in main
    run(
  File "/home/mario/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1562, in run
    model_runner_and_params = load_models_and_params(
  File "/home/mario/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/alphafold/models.py", line 161, in load_models_and_params
    params = get_model_haiku_params(
  File "/home/mario/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/alphafold/models.py", line 41, in get_model_haiku_params
    return utils.flat_params_to_haiku(params, fuse=use_fuse, to_jnp=to_jnp)
  File "/home/mario/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/model/utils.py", line 102, in flat_params_to_haiku
    P[scope][name] = jnp.array(array) if to_jnp else array
  File "/home/mario/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 2608, in array
    out_array: Array = lax_internal._convert_element_type(
  File "/home/mario/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 559, in _convert_element_type
    return convert_element_type_p.bind(operand, new_dtype=new_dtype,
  File "/home/mario/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/jax/_src/core.py", line 387, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/mario/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/jax/_src/core.py", line 391, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/mario/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/jax/_src/core.py", line 879, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/mario/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/jax/_src/dispatch.py", line 86, in apply_primitive
    outs = fun(*args)
ValueError: std::bad_cast

Alternatively, using as input an a3m alignment file, some other error lines are shown:
Traceback (most recent call last):
  File "/home/mario/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1496, in run
    = generate_input_feature(query_seqs_unique, query_seqs_cardinality, unpaired_msa, paired_msa,
  File "/home/mario/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1022, in generate_input_feature
    feature_dict = build_monomer_feature(
  File "/home/mario/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 875, in build_monomer_feature
    **pipeline.make_sequence_features(
  File "/home/mario/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/data/pipeline.py", line 40, in make_sequence_features
    features['aatype'] = residue_constants.sequence_to_onehot(
  File "/home/mario/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/common/residue_constants.py", line 580, in sequence_to_onehot
    raise ValueError(f'Invalid character in the sequence: {aa_type}')
ValueError: Invalid character in the sequence: -

Please, some advice to fix the issue will be welcome. Thank you very much in advance.

**Comment by YoshitakaMo** [comment]
> raise ValueError(f'Invalid character in the sequence: {aa_type}')
> ValueError: Invalid character in the sequence: -

It says that your input sequence `target.fasta` may contain an invalid character `-`. Please check your file first.

**Comment by bioinfcib** [comment]
> > raise ValueError(f'Invalid character in the sequence: {aa_type}')
> > ValueError: Invalid character in the sequence: -
> 
> It says that your input sequence `target.fasta` may contain an invalid character `-`. Please check your file first.

Thank you for your prompt reply. As I was said, that error is coming from an a3m align file as input, knowing that file format contains '-' character for deletions.

Additonally, what about the code error I was reporting firtstcoming from using as input a fasta file (with no '-' at all, of course)?

Thank you so much in advance for your replies.

**Comment by YoshitakaMo** [comment]
Ah, I missed there were two questions in your first comment. Sorry.
But,

> File "/home/mario/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/jax/_src/dispatch.py", line 86, in apply_primitive
> outs = fun(*args)
> ValueError: std::bad_cast

I have never encountered such an issue in localcolabfold. I have no idea about what caused this. Please check whether your input fasta is correct or the issue occurs in other fasta files.

**Comment by bioinfcib** [comment]
> Ah, I missed there were two questions in your first comment. Sorry. But,
> 
> > File "/home/mario/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/jax/_src/dispatch.py", line 86, in apply_primitive
> > outs = fun(*args)
> > ValueError: std::bad_cast
> 
> I have never encountered such an issue in localcolabfold. I have no idea about what caused this. Please check whether your input fasta is correct or the issue occurs with other fasta files.

Unfortunately, the same error occurs with whatever fasta files as input.

Regarding the issue with the a3m file as input, any ideas that could help us to fix it? If you think that checking files I'm using could help, please don't hesitate to say me. I'll be glad to send them you. Thank you very much.
