### ISSUE TITLE
403 Forbidden message 

### ISSUE THREAD

**Issue by jjv5** [YoshitakaMo/localcolabfold#273]
We received the following message when running colabfold_batch on a single small test sequence. We get this same result on two different compute clusters. Does this mean our IPs are banned?

```

SUBMIT:   0%|          | 0/150 [elapsed: 00:00 remaining: ?]
2024-11-04 14:04:16,767 Server didn't reply with json: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

2024-11-04 14:04:16,771 Could not get MSA/templates for 6A5J: MMseqs2 API is giving errors. Please confirm your input is a v
alid protein sequence. If error persists, please try again an hour later.
Traceback (most recent call last):
  File "/programs/x86_64-linux/colabfold/1.5.5/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1467, 
in run
    = get_msa_and_templates(jobname, query_sequence, a3m_lines, result_dir, msa_mode, use_templates,
  File "/programs/x86_64-linux/colabfold/1.5.5/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 827, i
n get_msa_and_templates
    a3m_lines = run_mmseqs2(
  File "/programs/x86_64-linux/colabfold/1.5.5/colabfold-conda/lib/python3.10/site-packages/colabfold/colabfold.py", line 21
0, in run_mmseqs2
    raise Exception(f'MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists
, please try again an hour later.')
Exception: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please tr
y again an hour later.
```

**Comment by YoshitakaMo** [comment]
Please report only issues related to installation on your local PC or macOS. If you can see the help message by running `colabfold_batch --help` or successfully run a test prediction, your installation was successful. For questions or requests about ColabFold features, please open an issue on the ColabFold repository.
