### ISSUE TITLE
'The number of positions must match the number of atoms'

### ISSUE THREAD

**Issue by xvazquezc** [YoshitakaMo/localcolabfold#30]
Hi there,
I was running the program when it crashed after generating the 3rd relaxed model. I ran the same protein before as a monomer (733 aa) with no issues and there was more than enough memory to continue (using a Volta V100-SXM2-32GB).

[Here](https://simtk.org/tracker/index.php?func=detail&aid=1763&group_id=161&atid=436) they mention that it's caused by OpenMM. The same OpenMM authors have a new tool that can fix this issues [PDBfixer](https://github.com/peastman/pdbfixer). Maybe  that helps.

Cheers,
Xabi

This was the command:
```
colabfold --input $INPUT \
--homooligomer 2 \
--msa_method precomputed \
--precomputed $MSA \
--output_dir ${OUTDIR} \
--max_recycle 3 \
--use_ptm \
--use_turbo \
--num_relax Top5
```
and the error:
```
[...]
model rank based on pLDDT
rank_1_model_5_ptm_seed_0 pLDDT:72.23
rank_2_model_4_ptm_seed_0 pLDDT:71.97
rank_3_model_3_ptm_seed_0 pLDDT:71.74
rank_4_model_1_ptm_seed_0 pLDDT:67.31
rank_5_model_2_ptm_seed_0 pLDDT:61.61
  0%|          | 0/5 [elapsed: 00:00 remaining: ?]
Traceback (most recent call last):
  File "/g/data1a/u71/xabi/colabfold/runner_af2advanced.py", line 289, in <module>
    relaxed_pdb_lines, _, _ = amber_relaxer.process(prot=outs[key]["unrelaxed_protein"])
  File "/g/data/u71/xabi/colabfold/alphafold/relax/relax.py", line 73, in process
    min_pdb = utils.overwrite_pdb_coordinates(pdb_str, min_pos)
  File "/g/data/u71/xabi/colabfold/alphafold/relax/utils.py", line 29, in overwrite_pdb_coordinates
    openmm_app.PDBFile.writeFile(topology, pos, f)
  File "/g/data1a/u71/xabi/colabfold/colabfold-conda/lib/python3.7/site-packages/simtk/openmm/app/pdbfile.py", line 283, in writeFile
    PDBFile.writeModel(topology, positions, file, keepIds=keepIds, extraParticleIdentifier=extraParticleIdentifier)
  File "/g/data1a/u71/xabi/colabfold/colabfold-conda/lib/python3.7/site-packages/simtk/openmm/app/pdbfile.py", line 331, in writeModel
    raise ValueError('The number of positions must match the number of atoms')
ValueError: The number of positions must match the number of atoms
```

**Comment by YoshitakaMo** [comment]
I have never encountered this error before, so I could not figure out the cause. But because the effect of relaxation is very limited and it can be performed by an alternative tool (including pdbfixer), so you can set `--num_relax None` to skip relaxation... just only a workaround...
