### ISSUE TITLE
Minimization failure on relax mode in recent version

### ISSUE THREAD

**Issue by gundalav** [YoshitakaMo/localcolabfold#37]
Hi, 

I'm trying the most recent version of localcolabfold, with this sequence:

`AVLKIIQGALDTRELLKAYQEEACAKNFGAFCVFVGIVRKEDNIQGLSFDIYEA`

My command line is this:

```
colabfold/bin/colabfold --input $INPUT_FASTA \
    --output $OUTPUT_DIR \
    --use_turbo \
    --use_ptm \
    --num_relax Top5 \
    --homooligomer 1
```

The error I get is this:

```
model rank based on pLDDT
rank_1_model_3_ptm_seed_0 pLDDT:88.87
rank_2_model_4_ptm_seed_0 pLDDT:88.20
rank_3_model_2_ptm_seed_0 pLDDT:86.50
rank_4_model_5_ptm_seed_0 pLDDT:85.70
rank_5_model_1_ptm_seed_0 pLDDT:84.93
  0%|          | 0/5 [elapsed: 00:00 remaining: ?]
Traceback (most recent call last):
  File "/home/ubuntu/storage1/colabfold/runner_af2advanced.py", line 289, in <module>
    relaxed_pdb_lines, _, _ = amber_relaxer.process(prot=outs[key]["unrelaxed_protein"])
  File "/home/ubuntu/storage1/colabfold/alphafold/relax/relax.py", line 62, in process
    max_outer_iterations=self._max_outer_iterations)
  File "/home/ubuntu/storage1/colabfold/alphafold/relax/amber_minimize.py", line 476, in run_pipeline
    max_attempts=max_attempts)
  File "/home/ubuntu/storage1/colabfold/alphafold/relax/amber_minimize.py", line 415, in _run_one_iteration
    raise ValueError(f"Minimization failed after {max_attempts} attempts.")
```

But when I replace it with :

`--num_relax None

`
It has no problem at all.

Before I never encounter such issue, even with the same sequence.
Is there a way we can deal with this?

The relaxed version is the preferred one, am I right?

Thanks and hope to hear from you again.

G.V.

**Comment by YoshitakaMo** [comment]
I just installed v.1.0.0 localcolabfold freshly and tried the prediction using your sequence and had no issues.

```
2021-11-16 17:36:42.283961: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
COLABFOLD_PATH is set to /home/moriwaki/Desktop/colabfold
Input ID: test
Input Sequence: AVLKIIQGALDTRELLKAYQEEACAKNFGAFCVFVGIVRKEDNIQGLSFDIYEA
homooligomer: 1
total_length: 54
output_dir: test
running mmseqs2
  0%|          | 0/150 [elapsed: 00:00 remaining: ?]
  0%|          | 0/5 [elapsed: 00:00 remaining: ?]
2021-11-16 17:36:47.590526: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-16 17:36:47.591246: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-11-16 17:36:47.591254: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]
2021-11-16 17:36:47.632798: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 3693090000 Hz
model_1_ptm_seed_0 recycles:3 tol:0.23 pLDDT:85.03 pTMscore:0.57
model_2_ptm_seed_0 recycles:3 tol:0.27 pLDDT:84.20 pTMscore:0.58
model_3_ptm_seed_0 recycles:3 tol:0.31 pLDDT:87.51 pTMscore:0.59
model_4_ptm_seed_0 recycles:3 tol:0.30 pLDDT:87.98 pTMscore:0.59
model_5_ptm_seed_0 recycles:3 tol:0.48 pLDDT:85.40 pTMscore:0.59
model rank based on pLDDT
rank_1_model_4_ptm_seed_0 pLDDT:87.98
rank_2_model_3_ptm_seed_0 pLDDT:87.51
rank_3_model_5_ptm_seed_0 pLDDT:85.40
rank_4_model_1_ptm_seed_0 pLDDT:85.03
rank_5_model_2_ptm_seed_0 pLDDT:84.20
  0%|          | 0/5 [elapsed: 00:00 remaining: ?]
predicted alignment error
predicted contacts
predicted distogram
predicted LDDT
```

But, I encountered a similar issue when I moved the `colabfold` directory from where it was initially. Have you done the same thing by any chance?

**Comment by gundalav** [comment]
Hi Yoshitaka-san, 

Yes, I think I did move the directory.
Then I completely delete the colabfold directory and reinstall again using `install_colabfold_linux.sh`.

How can I resolve the issue?

G.V.
