### ISSUE TITLE
assert "id" in df.columns and "sequence" in df.columns AssertionError

### ISSUE THREAD

**Issue by jihadsnobre** [YoshitakaMo/localcolabfold#46]
Thank you very much for this useful tool!

Installation worked fine, but now  I don't seem to be able to run colabfold. 

When I run:
`colabfold_batch --amber --templates --num-recycle 3 /Users/jihadsnobre1/Applications/input_files/seq.csv /Users/jihadsnobre1/Applications/output_files/`

I get this error: 
`Traceback (most recent call last):
  File "/Users/jihadsnobre1/Applications/colabfold_batch/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/Users/jihadsnobre1/Applications/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1288, in main
    queries, is_complex = get_queries(args.input, args.sort_queries_by)
  File "/Users/jihadsnobre1/Applications/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 385, in get_queries
    assert "id" in df.columns and "sequence" in df.columns
AssertionError`

Any idea of how to fix this? I wrote ta single protein sequence in a csv file and used that as input.

**Comment by konstin** [comment]
You're csv file needs an `id` column and a `sequence` column, one of which is missing

**Comment by jihadsnobre** [comment]
That was indeed the issue. Fixed it, many thanks!
