### ISSUE TITLE
How to insert 2 chains of a molecule?

### ISSUE THREAD

**Issue by Arjun1Singh** [YoshitakaMo/localcolabfold#53]
I have installed it on my m1 mac. It's working when I run without a chain break. 

But I want chain break in my protein. So as per (ColabFold AlphaFold2 notebook)- Use : to specify inter-protein chainbreaks for modeling complexes (supports homo- and hetro-oligomers) but its showing error in my system-

raise ValueError(f'Invalid character in the sequence: {aa_type}')
ValueError: Invalid character in the sequence: :

Inserted a .fasta file

**Comment by rkruegs123** [comment]
Following

**Comment by YoshitakaMo** [comment]
Here is my sample to predict a complex with chainbreak `:`.

```
>3KUD_complex
MTEYKLVVVGAGGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQVVIDGETCLLDILDTAGQEEYSAMRDQYMRTGEGFLC
VFAINNTKSFEDIHQYREQIKRVKDSDDVPMVLVGNKCDLAARTVESRQAQDLARSYGIPYIETSAKTRQGVEDAFYTLV
REIRQH:
PSKTSNTIRVFLPNKQRTVVNVRNGMSLHDCLMKALKVRGLQPECCAVFRLLHEHKGKKARLDWNTDAASLIGEELQVDF
L
```

Does it work on your machine?

**Comment by Arjun1Singh** [comment]
Error is coming-

2022-02-14 11:15:03,218 Could not generate input features sample: Invalid character in the sequence: :
Traceback (most recent call last):
  File "/Users/arjunsingh/dev/aplhafld/colabfold_batch/colabfold-conda/lib/python3.8/site-packages/colabfold/batch.py", line 1035, in run
    input_features = generate_input_feature(
  File "/Users/arjunsingh/dev/aplhafld/colabfold_batch/colabfold-conda/lib/python3.8/site-packages/colabfold/batch.py", line 750, in generate_input_feature
    feature_dict = build_monomer_feature(
  File "/Users/arjunsingh/dev/aplhafld/colabfold_batch/colabfold-conda/lib/python3.8/site-packages/colabfold/batch.py", line 621, in build_monomer_feature
    **pipeline.make_sequence_features(
  File "/Users/arjunsingh/dev/aplhafld/colabfold_batch/colabfold-conda/lib/python3.8/site-packages/alphafold/data/pipeline.py", line 40, in make_sequence_features
    features['aatype'] = residue_constants.sequence_to_onehot(
  File "/Users/arjunsingh/dev/aplhafld/colabfold_batch/colabfold-conda/lib/python3.8/site-packages/alphafold/common/residue_constants.py", line 580, in sequence_to_onehot
    raise ValueError(f'Invalid character in the sequence: {aa_type}')
ValueError: Invalid character in the sequence: :
2022-02-14 11:15:03,234 Done

**Comment by YoshitakaMo** [comment]
@Arjun1Singh I think your error resembles this issue https://github.com/sokrypton/ColabFold/issues/138. Is your colabfold_batch updated to the latest commit? If not, please update or reinstall, and try again.
