### ISSUE TITLE
Error when plotting via slurm

### ISSUE THREAD

**Issue by nayimgr** [YoshitakaMo/localcolabfold#59]
I've done the instalation succesfully and Localcolabfold functions as expected when I execute it locally (i.e., in the machine from which I'm working). Thanks for your work, btw!

However, I'm trying to run Localcolabfold in a remote machine as well using slurm to admin the jobs. When I do this, the MSA, prediction and relaxation happen as expected, but when it comes to plot the MSA accuracy and pLDDT matrices I get the following error:

```
Traceback (most recent call last):
  File "/xxx/localcolabfold/colabfold_batch/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/xxx/localcolabfold/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1336, in main
    zip_results=args.zip,
  File "/xxx/localcolabfold/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1113, in run
    query_sequence_len,
  File "/xxx/localcolabfold/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/plot.py", line 46, in plot_msa
    plt.figure(figsize=(8, 5), dpi=100)
  File "/xxx/localcolabfold/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/matplotlib/pyplot.py", line 545, in figure
    **kwargs)
  File "/xxx/localcolabfold/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 3261, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/xxx/localcolabfold/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 950, in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
  File "/xxx/localcolabfold/colabfold_batch/colabfold-conda/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":1"
```

I'm asuming this is just a lack of display (given that I'm executing it on remote). Any workaround to solve this?

Thanks a lot again!!

**Comment by YoshitakaMo** [comment]
I've found several related issues on StackOverflow.
- https://stackoverflow.com/questions/57044117/error-only-when-submitting-python-job-in-slurm
- https://stackoverflow.com/questions/19518352/tkinter-tclerror-couldnt-connect-to-display-localhost18-0

I think the solution is to modify these lines in your `/xxx/localcolabfold/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/plot.py`.

```patch
from pathlib import Path

import numpy as np
- from matplotlib import pyplot as plt
+ import matplotlib
+ matplotlib.use('Agg')
+ import matplotlib.pyplot as plt
```

Remove or comment out `from matplotlib import pyplot as plt` and add the three lines.

I don't know if this will work well since I don't have Slurm in my environment. So please let me know the result. Thank you in advance.

FYI, I'm using [OpenPBS](https://www.openpbs.org/) or [PBS Torque](https://adaptivecomputing.com/cherry-services/torque-resource-manager/) to manage the jobs on remote clustered machines, but such an issue occurred.

**Comment by nayimgr** [comment]
I apologize, I should have found those Stackoverflow threads myself... Thanks a lot. It worked perfectly well once those lines were changed.

Again, thanks for your work and the quick answer. Localcolabfold has been a huge help, keep it up!

**Comment by YoshitakaMo** [comment]
Thank you for the feedback! I also confirmed that this modification has no effect on OpenPBS queueing system. So, I'll make the patch for the Slurm users.
