### ISSUE TITLE
error

### ISSUE THREAD

**Issue by najibveto** [YoshitakaMo/localcolabfold#74]
**Describe the bug**
hello,
I installed the localcolabfold on my windows10/wsl2 following the instructions included into the github and i run the command as fellow:

`colabfold_batch --amber --templates --num-recycle 3 fff.fasta outputdir/`
and i got the following error:
```
WARNING: You are welcome to use the default MSA server, however keep in mind that it's a limited shared resource only capable of processing a few thousand MSAs per day. Please submit jobs only from a single IP address. We reserve the right to limit access to the server case-by-case when usage exceeds fair use.

If you require more MSAs, please host your own API and pass it to `--host-url`
2022-04-01 09:54:45,192 Running colabfold 1.2.0 (b532e910b15434f707f0b7460abc25c70fcb9b26)
2022-04-01 09:54:45,195 Found 8 citations for tools or databases
2022-04-01 09:54:53,540 Query 1/1: sp_O15552_FFAR2_HUMAN_Free_fatty_acid_receptor_2_OS_Homo_sapiens_OX_9606_GN_FFAR2_PE_1_SV_1 (length 330)
2022-04-01 09:55:03,288 Sequence 0 found templates: [b'5w0p_C' b'6i9k_A' b'6osa_R' b'5w0p_D' b'2ksb_A' b'6cmo_R' b'6c1q_B'
 b'5yhl_A' b'5ywy_A' b'6tod_A' b'6tod_B' b'2z73_A' b'3ayn_B' b'6wwz_R'
 b'6ko5_A' b'6c1r_B' b'5dhh_B' b'5unf_A' b'5dhg_B' b'6b73_A']
2022-04-01 09:55:03,557 Running model_3
Traceback (most recent call last):
  File "/home/najib/colabfold_batch/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/home/najib/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1467, in main
    save_pair_representations=args.save_pair_representations,
  File "/home/najib/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1169, in run
    prediction_callback=prediction_callback,
  File "/home/najib/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 246, in predict_structure
    feature_dict, random_seed=random_seed
  File "/home/najib/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/alphafold/model/model.py", line 135, in process_features
    random_seed=random_seed)
  File "/home/najib/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/alphafold/model/features.py", line 94, in np_example_to_features
    np_example=np_example, features=feature_names)
  File "/home/najib/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/alphafold/model/tf/proteins_dataset.py", line 165, in np_to_tensor_dict
    tensor_dict = parse_reshape_logic(tensor_dict, features_metadata)
  File "/home/najib/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/alphafold/model/tf/proteins_dataset.py", line 104, in parse_reshape_logic
    parsed_features[k] = tf.reshape(v, new_shape, name="reshape_%s" % k)
  File "/home/najib/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/najib/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1939, in _create_c_op
    raise ValueError(e.message)
ValueError: Cannot reshape a tensor with 1215380 elements to shape [3628,330,1] (1197240 elements) for '{{node reshape_msa}} = Reshape[T=DT_INT32, Tshape=DT_INT32](Const_6, reshape_msa/shape)' with input shapes: [3628,335], [3] and with input tensors computed as partial shapes: input[1] = [3628,330,1].
```

**Desktop (please complete the following information):**
 - Windows10 & WSL2
 - CUDA version 11.6

**Comment by YoshitakaMo** [comment]
In my environment (native Ubuntu 20.04.3 with CUDA 11.6.124), the prediction was successfully finished. The sequence file, O15552.fasta is downloaded from Uniprot.

```
$ colabfold_batch --amber --templates --num-recycle 3   --num-models 5 --model-order 1,2,3,4,5 --overwrite-existing-results O15552.fasta O15552

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a limited shared resource only capable of processing a few thousand MSAs per day. Please submit jobs only from a single IP address. We reserve the right to limit access to the server case-by-case when usage exceeds fair use.

If you require more MSAs, please host your own API and pass it to `--host-url`
2022-04-03 18:31:26,384 Running colabfold 1.2.0 (b532e910b15434f707f0b7460abc25c70fcb9b26)
2022-04-03 18:31:26,386 Found 8 citations for tools or databases
2022-04-03 18:31:30,279 Query 1/1: sp_O15552 (length 330)
COMPLETE: 100%|██████████████████████████████████████████████████████████████████████████████████| 150/150 [elapsed: 00:01 remaining: 00:00]
2022-04-03 18:31:42,949 Sequence 0 found templates: [b'6ibb_A' b'2ksb_A' b'6c1q_B' b'4n6h_A' b'6osa_R' b'5w0p_C' b'6wwz_R'
 b'5w0p_D' b'6cmo_R' b'6lfm_R' b'6lfo_R' b'2z73_A' b'3ayn_B' b'5dhh_B'
 b'6ko5_A' b'6c1r_B' b'5dhg_B' b'6b73_A' b'5yhl_A' b'5ywy_A']
2022-04-03 18:31:43,171 Running model_1
2022-04-03 18:34:05,795 model_1 took 140.3s (3 recycles) with pLDDT 84.1
2022-04-03 18:34:29,650 Running model_2
2022-04-03 18:35:23,139 model_2 took 52.3s (3 recycles) with pLDDT 79.2
2022-04-03 18:35:39,876 Running model_3
...
```

I couldn't figure out the cause. Please try installation again...

**Comment by najibveto** [comment]
thank u for your reply.
i installed on wsl and also on ubuntu but i got the same error.
should i remove it and install it again?
thank you.

**Comment by YoshitakaMo** [comment]
> should i remove it and install it again?

Not very promising, but give it a try.
Also, let me know which GPU and CUDA compiler you are using. i.e. `nvcc --version`, `nvidia-smi`, `nvidia-smi -L`.

**Comment by najibveto** [comment]
i tried the three commands and as u can see there is difference between nvcc -version and nvidia-smi L commands:
<pre><font color="#EF2929">╭╴</font><font color="#D3D7CF"><b></b></font> at <font color="#06989A"><b> ~</b></font> 
<font color="#EF2929">╰─</font><font color="#5FFF00"></font> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

<font color="#EF2929">╭╴</font><font color="#D3D7CF"><b></b></font> at <font color="#06989A"><b> ~</b></font> 
<font color="#EF2929">╰─</font><font color="#5FFF00"></font> nvidia-smi -L
GPU 0: NVIDIA GeForce GTX 1650 (UUID: GPU-8f480a3f-eda9-2ff4-56e2-f22e03187748)

<font color="#EF2929">╭╴</font><font color="#D3D7CF"><b></b></font> at <font color="#06989A"><b> ~</b></font> 
<font color="#EF2929">╰─</font><font color="#5FFF00"></font> nvidia-smi
Mon Apr  4 09:20:11 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
| 35%   31C    P5    10W /  75W |    502MiB /  3908MiB |     12%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1060      G   /usr/lib/xorg/Xorg                 59MiB |
|    0   N/A  N/A      1610      G   /usr/lib/xorg/Xorg                177MiB |
|    0   N/A  N/A      1820      G   cinnamon                           71MiB |
|    0   N/A  N/A     38869      G   /usr/lib/firefox/firefox          153MiB |
|    0   N/A  N/A     42126      G   /usr/lib/firefox/firefox            1MiB |
|    0   N/A  N/A     42957      G   ...RendererForSitePerProcess       26MiB |
+-----------------------------------------------------------------------------+

</pre>

**Comment by YoshitakaMo** [comment]
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

That's the cause. The version must be 11.1 or later. Please upgrade it and try again!

**Comment by najibveto** [comment]
yes thank you a lot, i removed the previous version and installed the 11.6 and it works fine.
thank you a lot.
