### ISSUE TITLE
Error when relaxing: jax._src.traceback_util.UnfilteredStackTrace: TypeError: take requires ndarray or scalar arguments, got <class 'list'> at position 0.

### ISSUE THREAD

**Issue by lucajovine** [YoshitakaMo/localcolabfold#8]
Hi, I just updated my code to the last commit and it works fine with the default num_relax = "None", but not with num_relax = "Top5":

>colabfold-conda/bin/python3.7 runner.py
2021-09-28 07:03:03.449188: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-09-28 07:03:05.429501: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-09-28 07:03:05.589721: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:0a:00.0 name: NVIDIA GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2021-09-28 07:03:05.589805: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 07:03:05.592761: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties:
pciBusID: 0000:42:00.0 name: NVIDIA GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.91GiB deviceMemoryBandwidth: 451.17GiB/s
2021-09-28 07:03:05.592788: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-09-28 07:03:05.603415: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-09-28 07:03:05.603500: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-09-28 07:03:05.610883: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2021-09-28 07:03:05.613852: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-09-28 07:03:05.625022: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2021-09-28 07:03:05.628477: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2021-09-28 07:03:05.629806: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-09-28 07:03:05.633270: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 07:03:05.639817: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 07:03:05.642759: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0, 1
2021-09-28 07:03:14.784927: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-09-28 07:03:14.786213: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-09-28 07:03:14.786232: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]
2021-09-28 07:03:14.860397: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 3393245000 Hz
ColabFold on Linux
homooligomer: '1'
total_length: '59'
working_directory: 'prediction_test_a5e17'
running mmseqs2
  0%|          | 0/5 [elapsed: 00:00 remaining: ?]
model_1_ptm_seed_0 recycles:3 tol:0.06 pLDDT:96.25 pTMscore:0.76
model_2_ptm_seed_0 recycles:3 tol:0.12 pLDDT:96.98 pTMscore:0.76
model_3_ptm_seed_0 recycles:3 tol:0.08 pLDDT:97.48 pTMscore:0.78
model_4_ptm_seed_0 recycles:3 tol:0.12 pLDDT:96.54 pTMscore:0.77
model_5_ptm_seed_0 recycles:3 tol:0.18 pLDDT:96.27 pTMscore:0.78
model rank based on pLDDT
rank_1_model_3_ptm_seed_0 pLDDT:97.48
rank_2_model_2_ptm_seed_0 pLDDT:96.98
rank_3_model_4_ptm_seed_0 pLDDT:96.54
rank_4_model_5_ptm_seed_0 pLDDT:96.27
rank_5_model_1_ptm_seed_0 pLDDT:96.25
  0%|          | 0/5 [elapsed: 00:00 remaining: ?]
Traceback (most recent call last):
  File "runner.py", line 758, in <module>
    relaxed_pdb_lines, _, _ = amber_relaxer.process(prot=outs[key]["unrelaxed_protein"])
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/relax/relax.py", line 62, in process
    max_outer_iterations=self._max_outer_iterations)
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/relax/amber_minimize.py", line 482, in run_pipeline
    ret.update(get_violation_metrics(prot))
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/relax/amber_minimize.py", line 356, in get_violation_metrics
    structural_violations, struct_metrics = find_violations(prot)
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/relax/amber_minimize.py", line 343, in find_violations
    "clash_overlap_tolerance": 1.5,  # Taken from model config.
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/model/folding.py", line 758, in find_structural_violations
    atomtype_radius, batch['residx_atom14_to_atom37'])
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/model/utils.py", line 39, in batched_gather
    return take_fn(params, indices)
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/model/utils.py", line 36, in <lambda>
    take_fn = lambda p, i: jnp.take(p, i, axis=axis)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 5384, in take
    mode)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/_src/api.py", line 414, in cache_miss
    donated_invars=donated_invars, inline=inline)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/core.py", line 1618, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/core.py", line 1609, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/core.py", line 1621, in process
    return trace.process_call(self, fun, tracers, params)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/core.py", line 615, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 623, in _xla_call_impl
    *unsafe_map(arg_spec, args))
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/linear_util.py", line 262, in memoized_fun
    ans = call(fun, *args)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 694, in _xla_callable
    return lower_xla_callable(fun, device, backend, name, donated_invars, *arg_specs).compile().unsafe_call
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 703, in lower_xla_callable
    fun, abstract_args, pe.debug_info_final(fun, "jit"))
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 1522, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 1500, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 5390, in _take
    _check_arraylike("take", a)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 559, in _check_arraylike
    raise TypeError(msg.format(fun_name, type(arg), pos))
jax._src.traceback_util.UnfilteredStackTrace: TypeError: take requires ndarray or scalar arguments, got <class 'list'> at position 0.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runner.py", line 758, in <module>
    relaxed_pdb_lines, _, _ = amber_relaxer.process(prot=outs[key]["unrelaxed_protein"])
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/relax/relax.py", line 62, in process
    max_outer_iterations=self._max_outer_iterations)
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/relax/amber_minimize.py", line 482, in run_pipeline
    ret.update(get_violation_metrics(prot))
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/relax/amber_minimize.py", line 356, in get_violation_metrics
    structural_violations, struct_metrics = find_violations(prot)
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/relax/amber_minimize.py", line 343, in find_violations
    "clash_overlap_tolerance": 1.5,  # Taken from model config.
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/model/folding.py", line 758, in find_structural_violations
    atomtype_radius, batch['residx_atom14_to_atom37'])
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/model/utils.py", line 39, in batched_gather
    return take_fn(params, indices)
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/model/utils.py", line 36, in <lambda>
    take_fn = lambda p, i: jnp.take(p, i, axis=axis)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 5384, in take
    mode)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 5390, in _take
    _check_arraylike("take", a)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 559, in _check_arraylike
    raise TypeError(msg.format(fun_name, type(arg), pos))
TypeError: take requires ndarray or scalar arguments, got <class 'list'> at position 0.

Any idea of what could be the problem? Thank you!

**Comment by YoshitakaMo** [comment]
Check the following points and write them here:
- check the cuda compiler version using `nvcc --version`. 11.1 or later required.
- Have you moved the `colabfold` directory after installation? If so, it causes the error at the relaxation step (AMBER minimization).

**Comment by lucajovine** [comment]
Hi, I did not move the colabfold directory but my nvcc version is indeed < 11.1:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

which however appears to be the latest version according to apt-get:

> sudo apt install nvidia-cuda-toolkit
Reading package lists... Done
Building dependency tree... 50%
Building dependency tree
Reading state information... Done
nvidia-cuda-toolkit is already the newest version (10.1.243-3).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

How to upgrade nvcc to 11.1 in a way that will be compatible with localcolabfold? Thanks again.

**Comment by YoshitakaMo** [comment]
See https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html and https://developer.nvidia.com/cuda-downloads.

If your OS is Ubuntu 20.04, the instruction is here:
```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
sudo apt-get update
sudo apt-get -y install cuda
```

**Comment by lucajovine** [comment]
Hello once more, done the above and got nvcc updated:

> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Aug_15_21:14:11_PDT_2021
Cuda compilation tools, release 11.4, V11.4.120
Build cuda_11.4.r11.4/compiler.30300941_0

However, this does not fix the problem:

> colabfold-conda/bin/python3.7 runner.py
2021-09-28 15:54:02.012725: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-09-28 15:54:03.755078: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-09-28 15:54:03.908135: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:0a:00.0 name: NVIDIA GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2021-09-28 15:54:03.908216: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 15:54:03.911159: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties:
pciBusID: 0000:42:00.0 name: NVIDIA GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.91GiB deviceMemoryBandwidth: 451.17GiB/s
2021-09-28 15:54:03.911186: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-09-28 15:54:03.921106: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-09-28 15:54:03.921171: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-09-28 15:54:03.928525: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2021-09-28 15:54:03.930969: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-09-28 15:54:03.942022: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2021-09-28 15:54:03.945674: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2021-09-28 15:54:03.946502: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-09-28 15:54:03.950344: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 15:54:03.956870: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 15:54:03.959823: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0, 1
2021-09-28 15:54:12.292372: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-09-28 15:54:12.293680: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-09-28 15:54:12.293695: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]
2021-09-28 15:54:12.371216: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 3393125000 Hz
ColabFold on Linux
homooligomer: '1'
total_length: '59'
working_directory: 'prediction_test_a5e17'
running mmseqs2
  0%|          | 0/5 [elapsed: 00:00 remaining: ?]
model_1_ptm_seed_0 recycles:3 tol:0.06 pLDDT:96.25 pTMscore:0.76
model_2_ptm_seed_0 recycles:3 tol:0.12 pLDDT:96.98 pTMscore:0.76
model_3_ptm_seed_0 recycles:3 tol:0.08 pLDDT:97.48 pTMscore:0.78
model_4_ptm_seed_0 recycles:3 tol:0.12 pLDDT:96.54 pTMscore:0.77
model_5_ptm_seed_0 recycles:3 tol:0.18 pLDDT:96.27 pTMscore:0.78
model rank based on pLDDT
rank_1_model_3_ptm_seed_0 pLDDT:97.48
rank_2_model_2_ptm_seed_0 pLDDT:96.98
rank_3_model_4_ptm_seed_0 pLDDT:96.54
rank_4_model_5_ptm_seed_0 pLDDT:96.27
rank_5_model_1_ptm_seed_0 pLDDT:96.25
  0%|          | 0/5 [elapsed: 00:00 remaining: ?]
Traceback (most recent call last):
  File "runner.py", line 758, in <module>
    relaxed_pdb_lines, _, _ = amber_relaxer.process(prot=outs[key]["unrelaxed_protein"])
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/relax/relax.py", line 62, in process
    max_outer_iterations=self._max_outer_iterations)
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/relax/amber_minimize.py", line 482, in run_pipeline
    ret.update(get_violation_metrics(prot))
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/relax/amber_minimize.py", line 356, in get_violation_metrics
    structural_violations, struct_metrics = find_violations(prot)
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/relax/amber_minimize.py", line 343, in find_violations
    "clash_overlap_tolerance": 1.5,  # Taken from model config.
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/model/folding.py", line 758, in find_structural_violations
    atomtype_radius, batch['residx_atom14_to_atom37'])
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/model/utils.py", line 39, in batched_gather
    return take_fn(params, indices)
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/model/utils.py", line 36, in <lambda>
    take_fn = lambda p, i: jnp.take(p, i, axis=axis)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 5384, in take
    mode)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/_src/api.py", line 414, in cache_miss
    donated_invars=donated_invars, inline=inline)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/core.py", line 1618, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/core.py", line 1609, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/core.py", line 1621, in process
    return trace.process_call(self, fun, tracers, params)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/core.py", line 615, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 623, in _xla_call_impl
    *unsafe_map(arg_spec, args))
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/linear_util.py", line 262, in memoized_fun
    ans = call(fun, *args)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 694, in _xla_callable
    return lower_xla_callable(fun, device, backend, name, donated_invars, *arg_specs).compile().unsafe_call
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 703, in lower_xla_callable
    fun, abstract_args, pe.debug_info_final(fun, "jit"))
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 1522, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 1500, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 5390, in _take
    _check_arraylike("take", a)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 559, in _check_arraylike
    raise TypeError(msg.format(fun_name, type(arg), pos))
jax._src.traceback_util.UnfilteredStackTrace: TypeError: take requires ndarray or scalar arguments, got <class 'list'> at position 0.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runner.py", line 758, in <module>
    relaxed_pdb_lines, _, _ = amber_relaxer.process(prot=outs[key]["unrelaxed_protein"])
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/relax/relax.py", line 62, in process
    max_outer_iterations=self._max_outer_iterations)
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/relax/amber_minimize.py", line 482, in run_pipeline
    ret.update(get_violation_metrics(prot))
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/relax/amber_minimize.py", line 356, in get_violation_metrics
    structural_violations, struct_metrics = find_violations(prot)
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/relax/amber_minimize.py", line 343, in find_violations
    "clash_overlap_tolerance": 1.5,  # Taken from model config.
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/model/folding.py", line 758, in find_structural_violations
    atomtype_radius, batch['residx_atom14_to_atom37'])
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/model/utils.py", line 39, in batched_gather
    return take_fn(params, indices)
  File "/usr/local/alphafold/localcolabfold/colabfold/alphafold/model/utils.py", line 36, in <lambda>
    take_fn = lambda p, i: jnp.take(p, i, axis=axis)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 5384, in take
    mode)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 5390, in _take
    _check_arraylike("take", a)
  File "/usr/local/alphafold/localcolabfold/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 559, in _check_arraylike
    raise TypeError(msg.format(fun_name, type(arg), pos))
TypeError: take requires ndarray or scalar arguments, got <class 'list'> at position 0.

**Comment by YoshitakaMo** [comment]
Hmm.. I have no idea. Does the problem still occur after reinstalling?

**Comment by lucajovine** [comment]
Yes. Also, I should add that I could run DeepMind's standalone code just fine, including relaxation, on the same machine... and this was with nvcc 10.1. So, considering the above, I doubt that's the culprit...

**Comment by zach-hensel** [comment]
Making the change here fixed this for me - https://github.com/deepmind/alphafold/commit/98caef21efa959e44ed01ab33cfb15ab04a39418 - this isn't a problem on colabfold yet, but I think will be if there's a fresh jax install?

Here's a patch that worked for me.
```
--- folding.py.bak	2021-09-28 22:46:32.529178748 +0100
+++ folding.py	2021-09-28 22:47:05.614184236 +0100
@@ -750,10 +750,10 @@
   # Compute the Van der Waals radius for every atom
   # (the first letter of the atom name is the element type).
   # Shape: (N, 14).
-  atomtype_radius = [
+  atomtype_radius = jnp.array([
       residue_constants.van_der_waals_radius[name[0]]
       for name in residue_constants.atom_types
-  ]
+  ])
   atom14_atom_radius = batch['atom14_atom_exists'] * utils.batched_gather(
       atomtype_radius, batch['residx_atom14_to_atom37'])
```
I guess a version of something relevant is different on the colab servers because this is not happening with colabfold.

**Comment by truatpasteurdotfr** [comment]
the above patch fixed the issue I have also seen! thanks a lot!

**Comment by lucajovine** [comment]
Hello and thank you - I confirm that the above patch works for me too!

One question though, why does one need a CUDA compiler driver >= 11.1 ? I reverted to my original installation, where the drive version is 10.1.243, and LocalColabFold seems to run just fine. For sure one does not need a driver > 11.1 to run DeepMind's code, so where does this requirement come in?

**Comment by zach-hensel** [comment]
> One question though, why does one need a CUDA compiler driver >= 11.1 ?

colab is running 11.1:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
```
localcolabfold installs 11.1 using conda and uses that python installation: `colabfold-conda/bin/python3.7 runner.py` works but `python runner.py` probably won't.

If you already have 11.1 working that means your nvidia drivers support 11.1 so it seems like a good requirement to have.

**Comment by lucajovine** [comment]
Got it, thanks! I guess we can close this issue, since the fix will presumably be incorporated into the next commit?

**Comment by YoshitakaMo** [comment]
Thanks, @zach-hensel, @truatpasteurdotfr, and @lucajovine. I'll incorporate the patch in the next commit.

**Comment by YoshitakaMo** [comment]
Now I updated the installers to fix jax compatibility issue. This change is compatible with https://github.com/sokrypton/ColabFold/commit/4a4552e38c89ce803ab03483a8e898943466d19a and https://github.com/deepmind/alphafold/commit/1d43aaff941c84dc56311076b58795797e49107b.
