### ISSUE TITLE
matplotlib issue in remote server

### ISSUE THREAD

**Issue by Raul-araya-secchi** [YoshitakaMo/localcolabfold#81]
Hi, I have been trying to run AF2 collar-batch on a GPU server that I only access remotely and that does not have a display and I 'm getting the following error, related to matplotlib and figure making I believe. How can this be fixed?

Thanks.

2022-04-28 10:19:16,547 reranking models by multimer
Traceback (most recent call last):
  File "/home/raul/bin/colabfold_batch/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/home/raul/bin/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1507, in main
    stop_at_score_below=args.stop_at_score_below,
  File "/home/raul/bin/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1233, in run
    query_sequence_len,
  File "/home/raul/bin/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/plot.py", line 73, in plot_msa
    plt.figure(figsize=(8, 5), dpi=dpi)
  File "/home/raul/bin/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/matplotlib/pyplot.py", line 545, in figure
    **kwargs)
  File "/home/raul/bin/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 3261, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/raul/bin/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 950, in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
  File "/home/raul/bin/colabfold_batch/colabfold-conda/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:11.0"

**Comment by YoshitakaMo** [comment]
Is it related to https://github.com/YoshitakaMo/localcolabfold/issues/59 ?
If so, the latest localcolabfold installer (or the updater) will suppress this issue.
