### ISSUE TITLE
AttributeError: "'data'"  in config_dict.py

### ISSUE THREAD

**Issue by Ni-Ar** [YoshitakaMo/localcolabfold#94]
**What is your question?**
I get a weird error that I cannot interpret. I report below the code to reproduce it.

**Computational environment**
OS: Linux CentOS 7.

Cuda:
 ```sh
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
```
```sh
gcc --version
gcc (conda-forge gcc 12.1.0-16) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
```

**To Reproduce**

input:
```sh
cat short_seqs2.fasta

>short_seq
PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASK
>qes_trohs
KSALEGGIGFHGKAMETIIVRVSTLPADLSRSIAESVERILTEKQEDSRGELIHIQAIP
```
Run as:
```sh
colabfold_batch --amber --templates --num-recycle 5 --use-gpu-relax --num-models 1 --model-type AlphaFold2-multimer-v1 short_seqs2.fasta ~/output/CF/short_seqs2
```

Errors I get to stderr:
```sh
WARNING: You are welcome to use the default MSA server, however keep in mind that it's a limited shared resource only capable of processing a few thousand MSAs per day. Please submit jobs only from a single IP address. We reserve the right to limit access to the server case-by-case when usage exceeds fair use.

If you require more MSAs:

* You can precompute all MSAs with `colabfold_search` or

* You can host your own API and pass it to `--host-url`
COMPLETE: 100%|██████████| 150/150 [elapsed: 00:03 remaining: 00:00]
Traceback (most recent call last):
  File "/users/software/miniconda/envs/colabfold/lib/python3.7/site-packages/ml_collections/config_dict/config_dict.py", line 903, in __getitem__
    field = self._fields[key]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/software/miniconda/envs/colabfold/lib/python3.7/site-packages/ml_collections/config_dict/config_dict.py", line 827, in __getattr__
    return self[attribute]
  File "/users/software/miniconda/envs/colabfold/lib/python3.7/site-packages/ml_collections/config_dict/config_dict.py", line 909, in __getitem__
    raise KeyError(self._generate_did_you_mean_message(key, str(e)))
KeyError: "'data'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/software/miniconda/envs/colabfold/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/users/software/miniconda/envs/colabfold/lib/python3.7/site-packages/colabfold/batch.py", line 1752, in main
    stop_at_score_below=args.stop_at_score_below,
  File "/users/software/miniconda/envs/colabfold/lib/python3.7/site-packages/colabfold/batch.py", line 1385, in run
    random_seed=random_seed,
  File "/users/software/miniconda/envs/colabfold/lib/python3.7/site-packages/colabfold/batch.py", line 350, in predict_structure
    use_templates,
  File "/users/software/miniconda/envs/colabfold/lib/python3.7/site-packages/colabfold/batch.py", line 279, in batch_input
    eval_cfg = model_config.data.eval
  File "/users/software/miniconda/envs/colabfold/lib/python3.7/site-packages/ml_collections/config_dict/config_dict.py", line 829, in __getattr__
    raise AttributeError(e)
AttributeError: "'data'"
```

stdout
```sh
2022-07-08 21:27:28,528 Running colabfold 1.3.0 (2a47c6f1459fbbdb5242cbc62173f9b513813cfa)
2022-07-08 21:27:34,541 --max-msa can not be used in combination with AlphaFold2-multimer (--max-msa ignored)
2022-07-08 21:28:03,707 Found 8 citations for tools or databases
2022-07-08 21:28:08,801 Query 1/2: short_seq (length 59)
2022-07-08 21:28:18,966 Sequence 0 found templates: ['6bgn_J', '2op8_A', '2opa_A', '4faz_C', '6ogm_D', '6ogm_J', '2x4k_A', '3ry0_A', '3ry0_B', '4fdx_A', '4fdx_B', '3ej3_B', '3ej3_L', '3ej9_D', '2orm_A', '2orm_C', '3m21_C', '3mb2_A', '3m20_A', '3m20_C']
2022-07-08 21:28:19,286 Running model_3
```

**Expected behavior**
I was hoping to be able to run a multimer type prediction, but no pdb file is computed. I can run single protein prediction without problem, I first encountered this problem when using a multifasta file for a multimer prediction.

```sh
ls -1 ~/output/CF/short_seqs2

cite.bibtex
config.json
log.txt
short_seq.a3m
short_seq_env
```

```sh
ls -1 ~/output/CF/short_seqs2/short_seq_env

bfd.mgnify30.metaeuk30.smag30.a3m
msa.sh
out.tar.gz
pdb70.m8
templates_101
uniref.a3m
```

**Comment by betainverse** [comment]
I had this problem also when running --model-type AlphaFold2-multimer-v2 , but it works fine if I am not running multimer.

**Comment by YoshitakaMo** [comment]
@Ni-Ar First, If you want to predict a multimer-type prediction, you should set the input fasta files as:
```
>short_seq
PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASK:
KSALEGGIGFHGKAMETIIVRVSTLPADLSRSIAESVERILTEKQEDSRGELIHIQAIP
```

Unlike the original AlphaFold2, the input format for multimers is different. Use `:` to concatenate two or more sequences.

`--model-type AlphaFold2-multimer-v1` arg is not necessary because colabfold can automatically find the appropriate model-type. `AlphaFold2-multimer-v1` is not recommended unless there is some particular reason because of its less accuracy than `AlphaFold2-multimer-v2`.

My prediction with the input file `short_seq.fasta` succeeded:

```
$ colabfold_batch \
  --amber \
  --templates \
  --num-recycle 3 \
  --use-gpu-relax \
  --num-models 5 \
  --model-order 1,2,3,4,5 \
  short_seq.fasta \
  short_seq

2022-07-19 00:15:19,442 Running colabfold 1.3.0 (26de12d3afb5f85d49d0c7db1b9371f034388395)
2022-07-19 00:15:19,773 --max-msa can not be used in combination with AlphaFold2-multimer (--max-msa ignored)
WARNING: You are welcome to use the default MSA server, however keep in mind that it's a limited shared resource only capable of processing a few thousand MSAs per day. Please submit jobs only from a single IP address. We reserve the right to limit access to the server case-by-case when usage exceeds fair use.

If you require more MSAs:

* You can precompute all MSAs with `colabfold_search` or

* You can host your own API and pass it to `--host-url`
2022-07-19 00:15:20,686 Found 8 citations for tools or databases
2022-07-19 00:15:22,574 Query 1/1: short_seq (length 118)
2022-07-19 00:15:22,921 Sleeping for 8s. Reason: PENDING
2022-07-19 00:15:31,270 Sleeping for 9s. Reason: RUNNING
COMPLETE: 100%|██████████████| 300/300 [elapsed: 00:18 remaining: 00:00]
2022-07-19 00:15:46,326 Sequence 0 found templates: ['4faz_C', '2orm_C', '3m21_F', '3ry0_A', '3ry0_B', '5tig_A', '2op8_A', '2opa_A', '6bgn_F', '4fdx_B', '7m59_A', '3abf_A', '3abf_F', '3mb2_C', '3mb2_E', '6ogm_A', '6ogm_E', '2x4k_A', '7puo_B', '4lkb_A']
2022-07-19 00:15:48,977 Sequence 1 found templates: ['7rd8_A']
2022-07-19 00:15:49,329 Sleeping for 5s. Reason: PENDING
COMPLETE: 100%|██████████████| 300/300 [elapsed: 00:06 remaining: 00:00]
2022-07-19 00:15:55,301 Running model_1
2022-07-19 00:16:10,611 model_1 took 15.3s (3 recycles) with pLDDT 66.7, ptmscore 0.595 and iptm 0.529
2022-07-19 00:16:30,610 Relaxation took 16.5s
2022-07-19 00:16:30,610 Running model_2
2022-07-19 00:16:35,732 model_2 took 5.1s (3 recycles) with pLDDT 58.8, ptmscore 0.516 and iptm 0.212
2022-07-19 00:16:49,707 Relaxation took 11.0s
2022-07-19 00:16:49,707 Running model_3
2022-07-19 00:17:03,413 model_3 took 13.7s (3 recycles) with pLDDT 59.1, ptmscore 0.536 and iptm 0.217
2022-07-19 00:17:16,564 Relaxation took 10.2s
2022-07-19 00:17:16,564 Running model_4
2022-07-19 00:17:21,688 model_4 took 5.1s (3 recycles) with pLDDT 59.5, ptmscore 0.522 and iptm 0.196
2022-07-19 00:17:35,589 Relaxation took 10.9s
2022-07-19 00:17:35,589 Running model_5
2022-07-19 00:17:40,698 model_5 took 5.1s (3 recycles) with pLDDT 59.4, ptmscore 0.522 and iptm 0.201
2022-07-19 00:17:54,557 Relaxation took 10.8s
2022-07-19 00:17:54,557 reranking models by multimer
2022-07-19 00:17:55,337 Done
```

@18217265596 Did you really produce this problem?

**Comment by betainverse** [comment]
Would you expect to be able to run the same prediction in a batch mode with an input file containing two different complexes? This is where I had a failure.

```
>short_seq1
PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASK:
KSALEGGIGFHGKAMETIIVRVSTLPADLSRSIAESVERILTEKQEDSRGELIHIQAIP
>short_seq2
AQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASK:
KSALEGGIGFHGKAMETIIVRVSTLPADLSRSIAESVERILTEKQEDSRGELIHIQA

```

**Comment by betainverse** [comment]
I think maybe the error only occurs if you specify
--model-type AlphaFold2-multimer-v1 or --model-type AlphaFold2-multimer-v2 but provide a fasta file with monomer sequences. I know it happens if you provide multiple monomer sequences, but I have not tried specifying alphafold multimer and providing only one monomer sequence.

**Comment by 18217265596** [comment]
@YoshitakaMo i did produce that problem
but i think its a format issue

format like that short_seq worked fine last night 
i guess no ploblem now thanks

**Comment by Ni-Ar** [comment]
Hi @YoshitakaMo,

thanks a lot for the help. It was a silly fasta file formatting issue! 🤦‍♂️

I manage to run the file:

```fasta
>short_seq
PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASK:
KSALEGGIGFHGKAMETIIVRVSTLPADLSRSIAESVERILTEKQEDSRGELIHIQAIP
```
with:
```sh
colabfold_batch --amber --templates --num-recycle 5 --use-gpu-relax --num-models 1 --model-type auto <IN> <OUT>
```
(I specified `--model-type auto` to be safe)
